import type { V4SourceRef, V4StudyContentPackage } from "../v4-content-package";

function sourceRefs(articleReference: string, pageStart: number, pageEnd = pageStart): V4SourceRef[] {
  return [
    { label: "BOE — Ley 55/2003 consolidada", reference: `BOE-A-2003-23101, ${articleReference}` },
    {
      label: "Temario principal",
      reference: pageStart === pageEnd ? `Temario_new.pdf, p. ${pageStart}` : `Temario_new.pdf, pp. ${pageStart}-${pageEnd}`,
      pageStart,
      pageEnd,
    },
  ];
}

const sources = {
  u01: sourceRefs("arts. 17-18", 241, 243),
  u02: sourceRefs("art. 19", 243, 245),
  u03: sourceRefs("art. 20", 245, 246),
  u04: sourceRefs("arts. 21-25", 246, 247),
  u05: sourceRefs("arts. 26-28", 247, 249),
  u06: sourceRefs("arts. 29-30.4", 249, 252),
  u07: sourceRefs("art. 30.5-6", 250, 252),
  u08: sourceRefs("arts. 31-32", 252, 254),
  u09: sourceRefs("art. 33", 254, 255),
  u10: sourceRefs("arts. 34-35", 255, 257),
  u11: sourceRefs("arts. 36-39", 257, 260),
  u12: sourceRefs("art. 40", 260, 261),
  u13: sourceRefs("arts. 41-42", 261, 263),
  u14: sourceRefs("arts. 43-45", 263, 264),
  u15: sourceRefs("arts. 70-71", 265, 267),
  u16: sourceRefs("art. 72", 267, 271),
  u17: sourceRefs("arts. 71.8 y 73", 266, 272),
  u18: sourceRefs("arts. 74-75", 272, 275),
};

type Unit = V4StudyContentPackage["units"][number];
type Concept = V4StudyContentPackage["concepts"][number];
type Flashcard = V4StudyContentPackage["flashcards"][number];

function unit(
  code: string,
  title: string,
  position: number,
  estimatedMinutes: number,
  studySummary: string,
  examKeys: string[],
  confusions: string[],
  traps: string[],
  sourceRefs: V4SourceRef[],
  mnemonics: string[] = [],
): Unit {
  return { code, title, position, estimatedMinutes, studySummary, examKeys, confusions, traps, mnemonics, sourceRefs };
}

function concept(code: string, unitCode: string, title: string, description: string, position: number): Concept {
  return { code, unitCode, title, description, position };
}

function card(
  number: number,
  conceptCode: string,
  type: Flashcard["type"],
  prompt: string,
  answer: string,
  position: number,
  sourceRefs: V4SourceRef[],
): Flashcard {
  return { code: `SMS-T13-F${String(number).padStart(2, "0")}`, conceptCode, type, prompt, answer, position, sourceRefs };
}

function mapPrimary(start: number, end: number, primaryConceptCode: string): V4StudyContentPackage["questionMappings"] {
  return Array.from({ length: end - start + 1 }, (_, offset) => ({
    questionCode: `SMS-T13-${String(start + offset).padStart(4, "0")}`,
    primaryConceptCode,
  }));
}

export const topic13EstatutoMarcoPackage = {
  version: "4.0",
  oppositionCode: "auxiliar-administrativo-sms",
  topicNumber: 13,
  sourceRevision: "BOE-A-2003-23101 consolidado (última actualización publicada 2023-03-01); gate editorial y contraste con Temario_new.pdf realizados 2026-08-19",
  units: [
    unit(
      "SMS-T13-U01", "Derechos del personal", 1, 6,
      "El Estatuto Marco distingue derechos individuales y colectivos. El régimen individual se extiende al personal temporal solo cuando la naturaleza del derecho lo permita. Entre los colectivos figuran sindicación, actividad sindical, huelga, negociación, representación, reunión y prevención; la huelga debe mantener los servicios esenciales de atención sanitaria.",
      ["Distinguir derechos individuales y colectivos.", "La extensión al temporal no es absoluta.", "La huelga conserva la garantía de servicios esenciales."],
      ["No confundir estabilidad propia del fijo con una garantía idéntica para cualquier nombramiento temporal."],
      ["Convertir la extensión del artículo 17.2 en equiparación incondicionada."],
      sources.u01,
    ),
    unit(
      "SMS-T13-U02", "Deberes del personal", 2, 7,
      "El artículo 19 reúne deberes profesionales y organizativos: lealtad y eficacia, actualización, cumplimiento diligente de instrucciones, colaboración, respeto a usuarios, información dentro de competencias, confidencialidad, uso eficiente de medios, documentación, seguridad y salud, incompatibilidades e identificación.",
      ["La clave suele estar en sujeto, verbo y límite del deber.", "Información al usuario y confidencialidad deben convivir."],
      ["No confundir un derecho del personal con su deber correlativo."],
      ["Omitir límites como el ámbito de competencias o el acceso por razón de las funciones."],
      sources.u02,
    ),
    unit(
      "SMS-T13-U03", "Adquisición de la condición fija", 3, 5,
      "La condición fija exige sucesivamente superar las pruebas, recibir nombramiento del órgano competente e incorporarse en plazo tras cumplir los requisitos formales. No acreditar los requisitos impide el nombramiento. La falta de incorporación solo produce el decaimiento previsto en el artículo 20.3 cuando es imputable al interesado y no obedece a causa justificada.",
      ["Secuencia: selección → nombramiento → incorporación.", "No acreditar requisitos y no incorporarse son supuestos distintos.", "El decaimiento exige imputabilidad y ausencia de causa justificada."],
      ["Una causa justificada no puede tratarse como falta de incorporación sancionable por el artículo 20.3."],
      ["Invertir la excepción y afirmar que una incorporación fallida justificada produce decaimiento."],
      sources.u03,
      ["S-N-I: Superar, Nombramiento, Incorporarse."],
    ),
    unit(
      "SMS-T13-U04", "Pérdida: renuncia, nacionalidad, separación e inhabilitación", 4, 9,
      "La pérdida de la condición fija comprende causas distintas que V4 diagnostica por separado. La renuncia es voluntaria, se solicita con 15 días y no inhabilita para acceder de nuevo. La pérdida de la nacionalidad relevante tiene la excepción de adquisición simultánea de otra habilitante. La separación disciplinaria debe ser firme. Las penas de inhabilitación tienen reglas propias: absoluta firme, especial para empleo o cargo si afecta al nombramiento y especial para la profesión cuando excede de seis años.",
      ["Renuncia: 15 días y límites de aceptación.", "Nacionalidad: importa la tomada en consideración para el nombramiento y la simultaneidad de la excepción.", "Separación e inhabilitación son causas distintas y no deben diagnosticarse conjuntamente."],
      ["No trasladar el umbral de seis años a toda inhabilitación."],
      ["Confundir una medida provisional con separación firme."],
      sources.u04,
    ),
    unit(
      "SMS-T13-U05", "Jubilación, incapacidad y recuperación", 5, 9,
      "La jubilación y la incapacidad permanente son causas extintivas distintas. La jubilación forzosa se sitúa en 65 años, con prolongación autorizada hasta 70 si existe capacidad funcional y lo permiten las necesidades organizativas; existe además prórroga por cotización insuficiente cuando resten seis años o menos. La incapacidad permanente total para la profesión habitual, absoluta para todo trabajo o gran invalidez produce pérdida. La recuperación se rige por el artículo 28, con una regla reforzada si la revisión de incapacidad se produce dentro de dos años.",
      ["Separar jubilación de incapacidad para diagnóstico.", "65/70 y ≤6 años son reglas distintas.", "Revisión de incapacidad dentro de dos años permite incorporación a misma categoría y área."],
      ["No convertir la prolongación hasta 70 en automática."],
      ["No atribuir a incapacidad temporal el efecto extintivo del artículo 27."],
      sources.u05,
    ),
    unit(
      "SMS-T13-U06", "Provisión y convocatorias", 6, 7,
      "La provisión se rige por igualdad, mérito, capacidad y publicidad, junto con planificación, integración, movilidad, coordinación y participación negociada. Se articula por selección, promoción interna, movilidad y reingreso. La selección fija es periódica y pública; las bases vinculan a Administración, órganos de selección y participantes y la convocatoria debe identificar plazas, requisitos, plazo, pruebas, baremos, programas y sistema de calificación.",
      ["Conocer principios y sistemas del artículo 29.", "Las pruebas deben adecuarse a las funciones de las plazas.", "Las bases publicadas vinculan a todos los sujetos del proceso."],
      ["No confundir sistemas de provisión con sistemas de selección."],
      ["Reducir el artículo 29 a los cuatro principios clásicos e ignorar los restantes."],
      sources.u06,
    ),
    unit(
      "SMS-T13-U07", "Requisitos de participación y discapacidad", 7, 6,
      "El artículo 30.5 fija requisitos de participación relativos a nacionalidad, titulación, capacidad, edad, separación e inhabilitación. La reserva para personas con discapacidad exige el porcentaje legal aplicable y un grado igual o superior al 33 %, además de superar el proceso y acreditar compatibilidad funcional.",
      ["Titulación dentro del plazo de solicitudes.", "18 años y no exceder jubilación forzosa.", "Separación disciplinaria: seis años anteriores."],
      ["No confundir porcentaje de reserva con grado de discapacidad."],
      ["Mover el momento de cumplimiento de titulación hasta el nombramiento."],
      sources.u07,
    ),
    unit(
      "SMS-T13-U08", "Sistemas, órganos y nombramientos de personal fijo", 8, 8,
      "El concurso-oposición es el sistema general; oposición y concurso pueden emplearse en los supuestos previstos. La convocatoria puede incluir período formativo o de prácticas con los límites legales. Los órganos de selección son colegiados y actúan con objetividad, imparcialidad, agilidad y eficacia. Los nombramientos favorecen a quienes obtengan mayor puntuación, se publican según determine cada servicio y expresan su ámbito.",
      ["Distinguir oposición, concurso y concurso-oposición.", "Miembros de órganos: condición profesional admitida y nivel académico suficiente.", "Publicación y ámbito del nombramiento son reglas del artículo 32."],
      ["No confundir órgano de selección con órgano que expide el nombramiento."],
      ["Suponer un orden fijo de las fases del concurso-oposición cuando lo determina la convocatoria."],
      sources.u08,
    ),
    unit(
      "SMS-T13-U09", "Selección de personal temporal", 9, 6,
      "La selección temporal busca cobertura inmediata con máxima agilidad, pero mantiene igualdad, mérito, capacidad, competencia, publicidad y celeridad. El nombramiento no genera fijeza. El período de prueba tiene límites diferentes según el personal y nunca puede superar la mitad de la duración del nombramiento cuando esta esté precisada; existe exención por prueba equivalente superada en los dos años anteriores.",
      ["Agilidad no elimina garantías.", "Nombramiento temporal nunca reconoce por sí solo fijeza.", "Distinguir 3 meses, 2 meses y límite de mitad del nombramiento."],
      ["No confundir urgencia con ausencia de principios selectivos."],
      ["Olvidar que la no superación de prueba debe obedecer a motivos razonados y comunicarse por escrito."],
      sources.u09,
    ),
    unit(
      "SMS-T13-U10", "Promoción interna", 10, 8,
      "La promoción interna permite al personal fijo acceder a categorías de igual o superior nivel académico con los requisitos del artículo 34 y preferencia de elección frente al acceso libre. La promoción interna temporal es voluntaria, responde a necesidades del servicio, mantiene al interesado activo en su categoría de origen, retribuye las funciones efectivas salvo trienios y no consolida nuevo nombramiento; sus procedimientos son objeto de negociación.",
      ["Regla general: titulación, servicio activo y dos años como fijo en origen.", "Excepción de titulación: cinco años y título del grupo inmediatamente inferior con límites.", "Promoción temporal no consolida derechos."],
      ["No confundir promoción interna definitiva con temporal."],
      ["Atribuir los trienios a la categoría temporalmente desempeñada."],
      sources.u10,
    ),
    unit(
      "SMS-T13-U11", "Movilidad, coordinación y comisiones de servicio", 11, 9,
      "La movilidad por razón del servicio y la voluntaria tienen presupuestos distintos. El artículo 38 contiene un núcleo autónomo de coordinación cuando las convocatorias afectan a más de un servicio de salud. El artículo 39 regula separadamente las comisiones de servicio: cobertura temporal de vacantes o puestos desatendidos y desempeño de funciones especiales, con reglas retributivas y reserva del puesto de origen.",
      ["Movilidad por razón del servicio exige resolución motivada.", "Coordinación mult-servicio: colaboración y Comisión de Recursos Humanos del SNS.", "Comisión de servicios: temporalidad, categoría/especialidad, retribución y reserva."],
      ["No diagnosticar coordinación de convocatorias y comisión de servicios como un solo conocimiento."],
      ["Confundir comisión temporal con provisión definitiva."],
      sources.u11,
    ),
    unit(
      "SMS-T13-U12", "Carrera profesional", 12, 6,
      "La carrera reconoce progresión individualizada por desarrollo en conocimientos, experiencia y objetivos. Las comunidades autónomas establecen mecanismos previa negociación. La Comisión de Recursos Humanos fija principios y criterios generales de homologación para reconocimiento mutuo y libre circulación; la adaptación de criterios de desarrollo profesional debe atender las condiciones del servicio o centro.",
      ["Carrera no equivale a antigüedad automática.", "Distinguir implantación autonómica y homologación general."],
      ["No atribuir a la Comisión la concesión individual de grados."],
      ["Omitir la negociación prevista en los apartados 1 y 4."],
      sources.u12,
    ),
    unit(
      "SMS-T13-U13", "Régimen retributivo: estructura y básicas", 13, 8,
      "El sistema se divide en retribuciones básicas y complementarias. La evaluación influye en parte de las complementarias ligadas a productividad y rendimiento; no cabe participación en ingresos y la deducción proporcional por jornada no realizada no es sanción. Las básicas son sueldo, trienios y dos pagas extraordinarias; sueldo y trienios se vinculan a categoría y titulación en los términos del artículo 42.",
      ["Básicas: sueldo, trienios, dos extras.", "El sueldo depende del título exigido para la categoría.", "Trienio: categoría del día de perfeccionamiento."],
      ["No confundir deducción de haberes con sanción."],
      ["Clasificar productividad como básica."],
      sources.u13,
    ),
    unit(
      "SMS-T13-U14", "Retribuciones complementarias y situaciones especiales", 14, 7,
      "Las complementarias pueden ser fijas o variables y retribuyen función, categoría, dedicación, actividad, productividad, objetivos y resultados. El artículo 43 distingue destino, específico, productividad, atención continuada y carrera. El temporal percibe básicas y complementarias de su nombramiento salvo trienios; los aspirantes en prácticas tienen como mínimo básicas, excluidos trienios, del grupo de ingreso.",
      ["Específico y productividad responden a factores distintos.", "Temporal y aspirante en prácticas tienen reglas especiales diferentes."],
      ["No confundir la excepción de trienios con exclusión general de complementos."],
      ["Asignar más de un específico por la misma circunstancia."],
      sources.u14,
    ),
    unit(
      "SMS-T13-U15", "Responsabilidad y potestad disciplinaria", 15, 6,
      "El personal responde por las faltas que cometa. El régimen disciplinario se rige por tipicidad, eficacia y proporcionalidad; el procedimiento añade celeridad/inmediatez/economía y garantías. La competencia corresponde al servicio donde se prestaban servicios al cometer la falta. Los indicios fundados de criminalidad suspenden la tramitación y se comunican al Ministerio Fiscal. No cabe analogía sancionadora.",
      ["Competencia por lugar de prestación al cometer la falta.", "Indicios penales: suspensión y Ministerio Fiscal.", "Tipicidad impide analogía."],
      ["No confundir responsabilidad disciplinaria con exclusión de otras responsabilidades."],
      ["Trasladar la competencia al servicio que expidió originariamente el nombramiento."],
      sources.u15,
    ),
    unit(
      "SMS-T13-U16", "Faltas y prescripción", 16, 9,
      "Las faltas son muy graves, graves y leves; la dificultad está en los elementos que cambian la gravedad en asistencia, desobediencia, incompatibilidades, prevención o acoso. La prescripción de faltas es un concepto propio: 4 años, 2 años y 6 meses; comienza al cometerse, se interrumpe con la notificación del inicio del procedimiento y vuelve a correr si este queda paralizado más de tres meses por causa no imputable.",
      ["Distinguir fronteras entre grados.", "Prescripción de faltas: dies a quo, interrupción y reinicio además del 4/2/6."],
      ["No usar los seis meses de ejecución de sanciones para prescripción de faltas."],
      ["Confundir una conducta residual leve con el tipo grave o muy grave sin comprobar requisitos."],
      sources.u16,
      ["Faltas: 4 años / 2 años / 6 meses."],
    ),
    unit(
      "SMS-T13-U17", "Sanciones", 17, 9,
      "El artículo 73 relaciona sanción, gravedad y efectos: separación, traslados, suspensión y apercibimiento. La prescripción de sanciones comparte 4/2/6 con las faltas, pero tiene dies a quo e interrupción propios. La cancelación de anotaciones es otro núcleo: se practica de oficio tras el cumplimiento a los 6 meses, 2 años o 4 años según gravedad y una anotación cancelada no computa para reincidencia.",
      ["Separación solo por muy grave; apercibimiento escrito solo por leve.", "Prescripción de sanciones y cancelación de anotaciones se diagnostican por separado."],
      ["No confundir firmeza/ejecución de la sanción con comisión de la falta."],
      ["Usar tres meses como umbral de paralización de ejecución: en sanciones es superior a seis meses."],
      sources.u17,
    ),
    unit(
      "SMS-T13-U18", "Procedimiento y medidas provisionales", 18, 8,
      "Las faltas graves y muy graves exigen procedimiento; en leves no es preceptiva la instrucción completa pero la audiencia es obligatoria. El artículo 74 garantiza presunción de inocencia, notificación y recusación, conocimiento de hechos y sanciones, alegaciones, prueba y asistencia. La suspensión provisional es una medida cautelar separada: en expediente disciplinario tiene límite general de seis meses y retribuciones básicas; los supuestos judiciales tienen reglas de duración y retribución específicas.",
      ["Leves: audiencia siempre.", "Procedimiento: celeridad, inmediatez y economía procesal.", "Suspensión judicial puede llegar hasta resolución y ciertas medidas >5 días implican ausencia de retribución."],
      ["No confundir suspensión provisional con sanción firme de suspensión de funciones."],
      ["Aplicar el máximo de seis meses a todo supuesto judicial."],
      sources.u18,
    ),
  ],
  concepts: [
    concept("SMS-T13-C01", "SMS-T13-U01", "Derechos individuales y colectivos", "Catálogo y naturaleza de derechos, extensión al temporal y límites de derechos colectivos.", 1),
    concept("SMS-T13-C02", "SMS-T13-U02", "Deberes estatutarios", "Obligaciones profesionales, organizativas, de información, confidencialidad, eficiencia, seguridad e identificación.", 1),
    concept("SMS-T13-C03", "SMS-T13-U03", "Requisitos sucesivos y efectos de la falta de acreditación o incorporación", "Secuencia para adquirir la condición fija y consecuencias de no acreditar requisitos o de no incorporarse en plazo cuando la falta es imputable al interesado y no obedece a causa justificada.", 1),
    concept("SMS-T13-C04", "SMS-T13-U04", "Causas de pérdida y renuncia", "Causas generales de extinción y requisitos, límites y efectos de la renuncia voluntaria.", 1),
    concept("SMS-T13-C05", "SMS-T13-U04", "Pérdida por nacionalidad", "Pérdida de la nacionalidad tomada en consideración para el nombramiento y excepción por adquisición simultánea de otra habilitante.", 2),
    concept("SMS-T13-C30", "SMS-T13-U04", "Pérdida por separación del servicio", "Firmeza, efecto extintivo, gravedad habilitante y consecuencias posteriores de la separación disciplinaria.", 3),
    concept("SMS-T13-C31", "SMS-T13-U04", "Pérdida por inhabilitación", "Reglas diferenciadas de inhabilitación absoluta, especial para empleo o cargo y especial para la profesión.", 4),
    concept("SMS-T13-C06", "SMS-T13-U05", "Jubilación", "Jubilación forzosa, prolongación del servicio activo y prórroga por cotización insuficiente.", 1),
    concept("SMS-T13-C32", "SMS-T13-U05", "Incapacidad permanente", "Grados de incapacidad permanente que determinan pérdida y su alcance.", 2),
    concept("SMS-T13-C07", "SMS-T13-U05", "Recuperación de la condición fija", "Recuperación tras nacionalidad o revisión de incapacidad, plazo de dos años y situación posterior.", 3),
    concept("SMS-T13-C08", "SMS-T13-U06", "Principios y sistemas de provisión", "Principios básicos y mecanismos legales para proveer plazas.", 1),
    concept("SMS-T13-C09", "SMS-T13-U06", "Convocatorias: periodicidad, bases y contenido", "Publicidad, adecuación de pruebas, fuerza vinculante y contenido mínimo de convocatorias.", 2),
    concept("SMS-T13-C10", "SMS-T13-U07", "Requisitos de participación y reserva por discapacidad", "Condiciones personales de acceso y reglas cuantitativas de la reserva.", 1),
    concept("SMS-T13-C11", "SMS-T13-U08", "Sistemas de selección y aspirantes en prácticas", "Concurso-oposición, oposición, concurso y régimen del período formativo o de prácticas.", 1),
    concept("SMS-T13-C12", "SMS-T13-U08", "Órganos de selección y nombramientos", "Naturaleza y composición de órganos y reglas de expedición, publicación y ámbito del nombramiento.", 2),
    concept("SMS-T13-C13", "SMS-T13-U09", "Selección, nombramiento y período de prueba temporal", "Principios, falta de fijeza y reglas del período de prueba temporal.", 1),
    concept("SMS-T13-C14", "SMS-T13-U10", "Promoción interna: acceso, requisitos y preferencia", "Nivel de titulación, requisitos, excepción y preferencia en elección de plaza.", 1),
    concept("SMS-T13-C15", "SMS-T13-U10", "Promoción interna temporal", "Voluntariedad, negociación, situación, retribución, falta de consolidación y mérito posible.", 2),
    concept("SMS-T13-C16", "SMS-T13-U11", "Movilidad por razón del servicio y movilidad voluntaria", "Reglas y contraste entre movilidad organizativa y voluntaria.", 1),
    concept("SMS-T13-C17", "SMS-T13-U11", "Coordinación y colaboración en convocatorias", "Regla del artículo 38 para convocatorias que afectan a más de un servicio de salud.", 2),
    concept("SMS-T13-C33", "SMS-T13-U11", "Comisiones de servicio", "Presupuestos, temporalidad, retribución y reserva del puesto de origen en comisiones de servicio.", 3),
    concept("SMS-T13-C18", "SMS-T13-U12", "Carrera profesional y homologación", "Implantación, progresión, homologación, adaptación y negociación de carrera profesional.", 1),
    concept("SMS-T13-C19", "SMS-T13-U13", "Estructura, criterios y reglas generales de retribución", "Estructura básica/complementaria, evaluación, participación en ingresos y deducción no sancionadora.", 1),
    concept("SMS-T13-C20", "SMS-T13-U13", "Retribuciones básicas y pagas extraordinarias", "Sueldo, trienios, categoría de perfeccionamiento y pagas extraordinarias.", 2),
    concept("SMS-T13-C21", "SMS-T13-U14", "Complementos retributivos", "Naturaleza y finalidad de destino, específico, productividad, atención continuada y carrera.", 1),
    concept("SMS-T13-C22", "SMS-T13-U14", "Retribuciones de temporales y aspirantes en prácticas", "Reglas especiales y exclusión de trienios en ambos supuestos.", 2),
    concept("SMS-T13-C23", "SMS-T13-U15", "Responsabilidad, competencia y principios disciplinarios", "Responsabilidad, servicio competente, criminalidad, tipicidad, analogía y proporcionalidad.", 1),
    concept("SMS-T13-C24", "SMS-T13-U16", "Clases y fronteras entre faltas", "Clasificación y elementos que distinguen faltas muy graves, graves y leves.", 1),
    concept("SMS-T13-C25", "SMS-T13-U16", "Prescripción de faltas", "Plazos por gravedad, dies a quo, interrupción y reinicio del cómputo.", 2),
    concept("SMS-T13-C26", "SMS-T13-U17", "Clases de sanciones y efectos", "Sanciones, gravedad habilitante, límites, destino y exclusiones asociadas.", 1),
    concept("SMS-T13-C27", "SMS-T13-U17", "Prescripción de sanciones", "Plazos, dies a quo, interrupción y reinicio de la prescripción de sanciones.", 2),
    concept("SMS-T13-C34", "SMS-T13-U17", "Cancelación de anotaciones disciplinarias", "Anotación de sanciones firmes, cancelación de oficio, plazos desde cumplimiento y efecto sobre reincidencia.", 3),
    concept("SMS-T13-C28", "SMS-T13-U18", "Procedimiento y garantías", "Necesidad de procedimiento, principios y derechos del inculpado.", 1),
    concept("SMS-T13-C29", "SMS-T13-U18", "Suspensión provisional y efectos", "Presupuestos, duración, retribuciones y efectos de la suspensión provisional disciplinaria o judicial.", 2),
  ],
  questionMappings: [
    ...mapPrimary(1, 4, "SMS-T13-C01"),
    ...mapPrimary(5, 10, "SMS-T13-C02"),
    ...mapPrimary(11, 13, "SMS-T13-C03"),
    ...mapPrimary(14, 17, "SMS-T13-C04"),
    ...mapPrimary(18, 18, "SMS-T13-C05"),
    ...mapPrimary(19, 19, "SMS-T13-C30"),
    ...mapPrimary(20, 20, "SMS-T13-C31"),
    ...mapPrimary(21, 22, "SMS-T13-C06"),
    ...mapPrimary(23, 23, "SMS-T13-C32"),
    ...mapPrimary(24, 26, "SMS-T13-C07"),
    ...mapPrimary(27, 28, "SMS-T13-C08"),
    ...mapPrimary(29, 31, "SMS-T13-C09"),
    ...mapPrimary(32, 35, "SMS-T13-C10"),
    ...mapPrimary(36, 39, "SMS-T13-C11"),
    ...mapPrimary(40, 41, "SMS-T13-C12"),
    ...mapPrimary(42, 45, "SMS-T13-C13"),
    ...mapPrimary(46, 49, "SMS-T13-C14"),
    ...mapPrimary(50, 52, "SMS-T13-C15"),
    ...mapPrimary(53, 58, "SMS-T13-C16"),
    ...mapPrimary(59, 59, "SMS-T13-C17"),
    ...mapPrimary(60, 61, "SMS-T13-C33"),
    ...mapPrimary(62, 63, "SMS-T13-C18"),
    ...mapPrimary(64, 67, "SMS-T13-C19"),
    ...mapPrimary(68, 70, "SMS-T13-C20"),
    ...mapPrimary(71, 73, "SMS-T13-C21"),
    ...mapPrimary(74, 75, "SMS-T13-C22"),
    ...mapPrimary(76, 80, "SMS-T13-C23"),
    ...mapPrimary(81, 86, "SMS-T13-C24"),
    ...mapPrimary(87, 88, "SMS-T13-C25"),
    ...mapPrimary(89, 93, "SMS-T13-C26"),
    ...mapPrimary(94, 94, "SMS-T13-C27"),
    ...mapPrimary(95, 95, "SMS-T13-C34"),
    ...mapPrimary(96, 97, "SMS-T13-C28"),
    ...mapPrimary(98, 99, "SMS-T13-C29"),
  ],
  flashcards: [
    card(1, "SMS-T13-C01", "direct", "¿Cómo se aplica el artículo 17 al personal temporal?", "En la medida en que la naturaleza de cada derecho lo permita.", 1, sources.u01),
    card(2, "SMS-T13-C01", "contrast", "¿Qué límite acompaña al derecho de huelga?", "Debe mantenerse en todo caso el servicio esencial de atención sanitaria.", 2, sources.u01),
    card(3, "SMS-T13-C02", "direct", "¿Qué exige la actualización profesional?", "Mantener actualizados conocimientos y aptitudes necesarios para las funciones.", 1, sources.u02),
    card(4, "SMS-T13-C02", "contrast", "¿Cómo conviven información al usuario y confidencialidad?", "Se informa dentro de las competencias sin quebrantar la reserva sobre información conocida por razón de las funciones.", 2, sources.u02),
    card(5, "SMS-T13-C03", "direct", "¿Cuáles son los tres requisitos sucesivos de adquisición?", "Superar pruebas, nombramiento competente e incorporación en plazo cumpliendo requisitos formales.", 1, sources.u03),
    card(6, "SMS-T13-C03", "exception", "¿Cuándo produce decaimiento la falta de incorporación?", "Cuando es imputable al interesado y no obedece a causa justificada; el efecto se limita a ese proceso selectivo.", 2, sources.u03),
    card(7, "SMS-T13-C04", "number_or_deadline", "¿Con qué antelación mínima se solicita la renuncia?", "Con 15 días respecto de la fecha en que se desee hacer efectiva.", 1, sources.u04),
    card(8, "SMS-T13-C04", "exception", "¿La renuncia impide obtener de nuevo la condición?", "No; puede volver a obtenerse mediante selección.", 2, sources.u04),
    card(9, "SMS-T13-C05", "direct", "¿Qué nacionalidad importa para la pérdida del artículo 23?", "La tomada en consideración para el nombramiento.", 1, sources.u04),
    card(10, "SMS-T13-C05", "exception", "¿Qué excepción evita la pérdida por nacionalidad?", "Adquirir simultáneamente otra nacionalidad que otorgue derecho de acceso.", 2, sources.u04),
    card(11, "SMS-T13-C30", "direct", "¿Cuándo la separación causa pérdida de la condición?", "Cuando la sanción de separación del servicio es firme.", 1, sources.u04),
    card(12, "SMS-T13-C30", "number_or_deadline", "¿Qué exclusión sigue a la ejecución de la separación?", "Durante seis años no puede concurrir a selección para fijo ni prestar servicios estatutarios temporales, además de los restantes efectos legales.", 2, sources.u17),
    card(13, "SMS-T13-C31", "contrast", "¿Cómo se diferencian las inhabilitaciones del artículo 25?", "La absoluta firme causa pérdida; la especial para empleo/cargo si afecta al nombramiento; la especial profesional si excede de seis años.", 1, sources.u04),
    card(14, "SMS-T13-C31", "number_or_deadline", "¿Exactamente seis años de inhabilitación especial profesional superan el umbral?", "No; la ley exige que exceda de seis años.", 2, sources.u04),
    card(15, "SMS-T13-C06", "number_or_deadline", "¿Cuáles son los números clave de jubilación?", "65 años forzosa; prolongación autorizada hasta 70; prórroga por cotización si faltan seis años o menos.", 1, sources.u05),
    card(16, "SMS-T13-C06", "exception", "¿La prolongación hasta 70 es automática?", "No; exige capacidad funcional y autorización según necesidades organizativas.", 2, sources.u05),
    card(17, "SMS-T13-C32", "contrast", "¿Qué incapacidades permanentes extinguen la condición?", "Total para la profesión habitual, absoluta para todo trabajo y gran invalidez.", 1, sources.u05),
    card(18, "SMS-T13-C32", "contrast", "¿Incapacidad temporal equivale a la incapacidad extintiva del artículo 27?", "No.", 2, sources.u05),
    card(19, "SMS-T13-C07", "number_or_deadline", "¿Qué ocurre si la incapacidad se revisa dentro de dos años?", "Existe derecho a incorporarse a plaza de la misma categoría y área de salud.", 1, sources.u05),
    card(20, "SMS-T13-C07", "exception", "Fuera de la revisión dentro de dos años, ¿qué situación acompaña a la recuperación?", "Declaración simultánea en excedencia voluntaria y posible reingreso sin tiempo mínimo de permanencia.", 2, sources.u05),
    card(21, "SMS-T13-C08", "direct", "¿Qué cuatro principios clásicos encabezan la provisión?", "Igualdad, mérito, capacidad y publicidad.", 1, sources.u06),
    card(22, "SMS-T13-C08", "direct", "¿Qué sistemas de provisión enumera el artículo 29.2?", "Selección, promoción interna, movilidad y reingreso al servicio activo.", 2, sources.u06),
    card(23, "SMS-T13-C09", "direct", "¿A quién vinculan convocatorias y bases?", "A Administración, tribunales u órganos de selección y participantes.", 1, sources.u06),
    card(24, "SMS-T13-C09", "direct", "¿A qué deben adecuarse contenidos y pruebas?", "A las funciones a desarrollar en las plazas, incluida cuando proceda la lengua oficial conforme a norma autonómica.", 2, sources.u06),
    card(25, "SMS-T13-C10", "number_or_deadline", "¿Qué límites de edad y separación son examinables?", "18 años cumplidos, no exceder jubilación forzosa y no haber sido separado en los seis años anteriores.", 1, sources.u07),
    card(26, "SMS-T13-C10", "number_or_deadline", "¿Qué grado de discapacidad exige la reserva?", "Igual o superior al 33 %, junto con el cupo legal aplicable y compatibilidad funcional.", 2, sources.u07),
    card(27, "SMS-T13-C11", "contrast", "¿Cuál es el sistema general y qué alternativas existen?", "Concurso-oposición como regla; oposición o concurso en los supuestos previstos.", 1, sources.u08),
    card(28, "SMS-T13-C11", "contrast", "¿Qué diferencia concurso y oposición?", "La oposición usa pruebas; el concurso valora méritos conforme a baremo.", 2, sources.u08),
    card(29, "SMS-T13-C12", "direct", "¿Cómo actúan los órganos de selección?", "Como órganos colegiados con objetividad, imparcialidad, agilidad y eficacia.", 1, sources.u08),
    card(30, "SMS-T13-C12", "direct", "¿Qué debe indicar expresamente el nombramiento fijo?", "El ámbito al que corresponde, conforme a convocatoria y disposiciones del servicio.", 2, sources.u08),
    card(31, "SMS-T13-C13", "direct", "¿Qué principios conserva la selección temporal pese a su agilidad?", "Igualdad, mérito, capacidad, competencia, publicidad y celeridad.", 1, sources.u09),
    card(32, "SMS-T13-C13", "number_or_deadline", "¿Qué límites tiene el período de prueba?", "Tres meses para los supuestos legales indicados, dos para el resto y nunca más de la mitad del nombramiento si su duración está precisada.", 2, sources.u09),
    card(33, "SMS-T13-C14", "number_or_deadline", "¿Qué antigüedad ordinaria exige promoción interna?", "Al menos dos años como fijo en la categoría de procedencia, además de titulación y servicio activo.", 1, sources.u10),
    card(34, "SMS-T13-C14", "exception", "¿Qué exige la excepción de titulación del artículo 34.5?", "Cinco años en la categoría de origen y titulación del grupo inmediatamente inferior, con los límites profesionales legales.", 2, sources.u10),
    card(35, "SMS-T13-C15", "direct", "¿Qué situación mantiene quien ejerce promoción interna temporal?", "Servicio activo en la categoría de origen, cobrando las funciones efectivas salvo trienios del nombramiento original.", 1, sources.u10),
    card(36, "SMS-T13-C15", "direct", "¿Consolida nuevo nombramiento la promoción interna temporal?", "No; tampoco consolida derechos retributivos, aunque puede valorarse como mérito.", 2, sources.u10),
    card(37, "SMS-T13-C16", "contrast", "¿Qué diferencia el origen de movilidad por servicio y voluntaria?", "La primera responde a necesidades organizativas y resolución motivada; la segunda se articula mediante procedimientos voluntarios de concurso.", 1, sources.u11),
    card(38, "SMS-T13-C16", "number_or_deadline", "Con cambio de servicio, ¿qué plazos siguen al destino por movilidad voluntaria?", "Cese en tres días y toma de posesión en un mes desde el cese.", 2, sources.u11),
    card(39, "SMS-T13-C17", "direct", "¿Cuándo se activa el artículo 38?", "Cuando convocatorias de provisión, selección o movilidad afectan a más de un servicio de salud.", 1, sources.u11),
    card(40, "SMS-T13-C17", "direct", "¿Qué fija la Comisión de Recursos Humanos en ese supuesto?", "Criterios y principios sobre periodicidad y coordinación, primando la colaboración entre servicios.", 2, sources.u11),
    card(41, "SMS-T13-C33", "direct", "¿Qué presupuestos básicos tiene una comisión para cubrir vacante o puesto desatendido?", "Necesidades del servicio, temporalidad y personal estatutario de la categoría y especialidad correspondientes.", 1, sources.u11),
    card(42, "SMS-T13-C33", "contrast", "¿Cómo varía la retribución entre vacante y funciones especiales?", "En vacante se cobra el puesto efectivo salvo que sea inferior al origen; en funciones especiales se mantienen retribuciones de origen. Siempre existe reserva de origen.", 2, sources.u11),
    card(43, "SMS-T13-C18", "direct", "¿Qué reconoce la carrera profesional?", "Progresión individualizada por conocimientos, experiencia y cumplimiento de objetivos.", 1, sources.u12),
    card(44, "SMS-T13-C18", "contrast", "¿Quién implanta y quién homologa la carrera?", "Las comunidades autónomas establecen mecanismos previa negociación; la Comisión fija criterios generales de homologación.", 2, sources.u12),
    card(45, "SMS-T13-C19", "direct", "¿Cómo se estructura el sistema retributivo?", "En retribuciones básicas y complementarias.", 1, sources.u13),
    card(46, "SMS-T13-C19", "contrast", "¿La deducción por jornada no realizada es sanción?", "No; es deducción proporcional sin carácter sancionador, sin perjuicio de una sanción que pudiera corresponder.", 2, sources.u13),
    card(47, "SMS-T13-C20", "direct", "¿Cuáles son las retribuciones básicas?", "Sueldo, trienios y pagas extraordinarias.", 1, sources.u13),
    card(48, "SMS-T13-C20", "number_or_deadline", "¿Cuántas pagas extraordinarias existen y cuándo se devengan preferentemente?", "Dos al año, preferentemente en junio y diciembre.", 2, sources.u13),
    card(49, "SMS-T13-C21", "direct", "Enumera los complementos del artículo 43.2.", "Destino, específico, productividad, atención continuada y carrera.", 1, sources.u14),
    card(50, "SMS-T13-C21", "contrast", "¿Qué diferencia específico y productividad?", "El específico retribuye condiciones particulares del puesto; productividad, rendimiento, iniciativa y contribución a objetivos previa evaluación.", 2, sources.u14),
    card(51, "SMS-T13-C22", "contrast", "¿Qué cobra el temporal frente al aspirante en prácticas?", "El temporal, todas las básicas y complementarias de su nombramiento salvo trienios; el aspirante, como mínimo las básicas sin trienios del grupo de ingreso.", 1, sources.u14),
    card(52, "SMS-T13-C22", "exception", "¿Qué exclusión común aparece en ambos regímenes?", "Los trienios.", 2, sources.u14),
    card(53, "SMS-T13-C23", "contrast", "¿Qué principios corresponden al régimen y cuáles al procedimiento?", "Régimen: tipicidad, eficacia y proporcionalidad; procedimiento: celeridad/inmediatez/economía y garantías.", 1, sources.u15),
    card(54, "SMS-T13-C23", "mini_case", "Aparecen indicios fundados de criminalidad durante el expediente. ¿Qué ocurre?", "Se suspende la tramitación y se ponen los hechos en conocimiento del Ministerio Fiscal.", 2, sources.u15),
    card(55, "SMS-T13-C24", "contrast", "¿Qué umbrales de inasistencia distinguen muy grave y grave?", "Muy grave: más de 5 días seguidos o 7 faltas en 2 meses; grave: más de 3 días seguidos o 5 en 2 meses cuando no sea muy grave.", 1, sources.u16),
    card(56, "SMS-T13-C24", "contrast", "¿Qué elemento puede elevar desobediencia a muy grave?", "Que sea notoria y manifiesta respecto de órdenes funcionales, con la excepción legal de órdenes manifiestamente contrarias a norma general.", 2, sources.u16),
    card(57, "SMS-T13-C25", "number_or_deadline", "¿Cuándo prescriben las faltas?", "Muy graves 4 años, graves 2 años y leves 6 meses.", 1, sources.u16),
    card(58, "SMS-T13-C25", "direct", "¿Cuándo empieza y se interrumpe la prescripción de una falta?", "Empieza al cometerse y se interrumpe con la notificación del acuerdo de iniciación.", 2, sources.u16),
    card(59, "SMS-T13-C26", "contrast", "Relaciona separación, traslados y apercibimiento con gravedad.", "Separación y traslado con cambio de localidad: muy graves; traslado sin cambio: graves; apercibimiento escrito: leves.", 1, sources.u17),
    card(60, "SMS-T13-C26", "number_or_deadline", "¿Cuáles son los límites de suspensión de funciones?", "Muy grave: 2 a 6 años; grave: hasta 2 años; si no supera 6 meses conserva destino.", 2, sources.u17),
    card(61, "SMS-T13-C27", "number_or_deadline", "¿Cuándo prescriben las sanciones?", "4 años, 2 años y 6 meses según deriven de faltas muy graves, graves o leves.", 1, sources.u17),
    card(62, "SMS-T13-C27", "contrast", "¿Qué diferencia su dies a quo del de las faltas?", "La sanción parte de la firmeza de la resolución o del quebrantamiento si la ejecución comenzó; la falta parte de su comisión.", 2, sources.u17),
    card(63, "SMS-T13-C34", "number_or_deadline", "¿Cuándo se cancelan de oficio las anotaciones?", "Desde el cumplimiento: 6 meses si leve, 2 años si grave y 4 años si muy grave.", 1, sources.u17),
    card(64, "SMS-T13-C34", "direct", "¿Qué efecto tiene una anotación cancelada?", "No puede computarse a efectos de reincidencia.", 2, sources.u17),
    card(65, "SMS-T13-C28", "contrast", "¿Qué diferencia procedimental existe para las faltas leves?", "No requieren la instrucción completa prevista para graves/muy graves, pero la audiencia al inculpado es obligatoria.", 1, sources.u18),
    card(66, "SMS-T13-C28", "direct", "¿Qué derechos de defensa destaca el artículo 74.2?", "Presunción de inocencia, notificación y recusación, conocimiento de imputación y sanciones, alegaciones, prueba, asistencia sindical y letrado.", 2, sources.u18),
    card(67, "SMS-T13-C29", "number_or_deadline", "¿Qué límite tiene la suspensión provisional por expediente disciplinario?", "Máximo seis meses salvo paralización imputable al interesado, con retribuciones básicas salvo incomparecencia.", 1, sources.u18),
    card(68, "SMS-T13-C29", "exception", "¿Qué sucede si una medida judicial impide trabajar más de cinco días consecutivos?", "Procede suspensión provisional sin derecho a retribuciones mientras dure la prisión provisional u otra medida impeditiva.", 2, sources.u18),
  ],
} satisfies V4StudyContentPackage;
