export type Topic13GapQuestionCandidate = {
  questionCode: string;
  conceptCode: string;
  dimension: string;
  question: string;
  options: readonly [string, string, string, string];
  correctOption: "A" | "B" | "C" | "D";
  explanation: string;
  sourceReference: string;
  documentReference: "Temario_new.pdf";
  pageStart: number;
  pageEnd: number;
  trapType: string;
};

function q(
  questionCode: string,
  conceptCode: string,
  dimension: string,
  question: string,
  options: readonly [string, string, string, string],
  correctOption: Topic13GapQuestionCandidate["correctOption"],
  explanation: string,
  sourceReference: string,
  pageStart: number,
  pageEnd: number,
  trapType: string,
): Topic13GapQuestionCandidate {
  return { questionCode, conceptCode, dimension, question, options, correctOption, explanation, sourceReference, documentReference: "Temario_new.pdf", pageStart, pageEnd, trapType };
}

export const topic13CoverageGapQuestions = [
  q("SMS-T13-0100", "SMS-T13-C03", "mini_case_exception", "Un aspirante nombrado no se incorpora dentro del plazo porque una causa acreditada y ajena a su voluntad se lo impide. Según el artículo 20.3, ¿qué consecuencia se produce por esa falta de incorporación?", ["Decae en todo caso su derecho derivado de ese proceso selectivo.", "No opera el decaimiento automático del artículo 20.3, al faltar imputabilidad y ausencia de justificación.", "Queda inhabilitado durante seis años para nuevos procesos selectivos.", "Se transforma automáticamente el nombramiento en temporal hasta que pueda incorporarse."], "B", "El decaimiento exige conjuntamente que la falta de incorporación sea imputable al interesado y que no obedezca a causas justificadas.", "Ley 55/2003, art. 20.3", 245, 246, "excepcion_condiciones"),

  q("SMS-T13-0101", "SMS-T13-C05", "scope", "¿Qué pérdida de nacionalidad contempla el artículo 23 como causa de pérdida de la condición de personal estatutario?", ["La de cualquier nacionalidad que posea el interesado al tiempo del cese.", "La tomada en consideración para el nombramiento, salvo la excepción legal de adquisición simultánea.", "Únicamente la nacionalidad española, cualquiera que fuese la utilizada para acceder.", "Solo la nacionalidad de un Estado miembro de la Unión Europea."], "B", "El artículo 23 se refiere específicamente a la nacionalidad tomada en consideración para el nombramiento.", "Ley 55/2003, art. 23", 246, 247, "literalidad_sujeto"),
  q("SMS-T13-0102", "SMS-T13-C05", "timing_exception", "Una persona pierde la nacionalidad que permitió su nombramiento y adquiere otra nacionalidad habilitante tres meses después. ¿Permite esa adquisición posterior aplicar la excepción del artículo 23 para evitar la pérdida inicial de la condición?", ["Sí, porque basta con adquirir otra nacionalidad habilitante antes de seis meses.", "Sí, siempre que la nueva nacionalidad sea de un Estado de la Unión Europea.", "No, la excepción exige que la adquisición de la otra nacionalidad habilitante sea simultánea a la pérdida.", "No, porque ninguna nueva nacionalidad permite recuperar después la condición."], "C", "La excepción del artículo 23 exige simultaneidad; una eventual recuperación posterior se rige por el artículo 28, no convierte en simultánea la adquisición.", "Ley 55/2003, arts. 23 y 28.1", 246, 249, "cambio_condicion"),
  q("SMS-T13-0103", "SMS-T13-C05", "contrast_non_relevant_nationality", "Una persona posee dos nacionalidades, pero solo una fue tomada en consideración para su nombramiento estatutario. Si pierde la otra y conserva la habilitante utilizada para acceder, ¿qué efecto prevé el artículo 23?", ["Pierde la condición por la mera reducción del número de nacionalidades.", "Queda suspendida hasta que acredite de nuevo ambas nacionalidades.", "No se produce por ese hecho la pérdida prevista en el artículo 23.", "Debe solicitar la recuperación de la condición conforme al artículo 28."], "C", "La causa legal se conecta con la pérdida de la nacionalidad tomada en consideración para el nombramiento, no con cualquier nacionalidad adicional.", "Ley 55/2003, art. 23", 246, 247, "sujeto_relevante"),

  q("SMS-T13-0104", "SMS-T13-C30", "effect", "¿Qué efecto produce una sanción disciplinaria firme de separación del servicio?", ["La suspensión temporal del nombramiento durante un máximo de seis años.", "La pérdida de la condición de personal estatutario.", "La excedencia voluntaria automática con reserva de plaza.", "El traslado forzoso a otro servicio de salud sin pérdida de condición."], "B", "Los artículos 21.c, 24 y 73.1.a conectan la separación firme con la pérdida de la condición.", "Ley 55/2003, arts. 21.c, 24 y 73.1.a", 246, 272, "efecto"),
  q("SMS-T13-0105", "SMS-T13-C30", "severity", "La sanción de separación del servicio puede imponerse:", ["Por faltas muy graves y graves cuando exista reincidencia.", "Solo por la comisión de faltas muy graves.", "Por cualquier falta si existe daño económico cuantificable.", "Solo por faltas graves cuando no proceda suspensión de funciones."], "B", "El artículo 73.1.a reserva la separación del servicio a las faltas muy graves.", "Ley 55/2003, art. 73.1.a", 271, 272, "gravedad_habilitante"),
  q("SMS-T13-0106", "SMS-T13-C30", "future_effect", "Tras ejecutarse una sanción de separación del servicio, ¿qué límite temporal establece el artículo 73.1.a?", ["Durante cuatro años no puede participar en movilidad, aunque sí acceder de nuevo por selección.", "Durante seis años no puede concurrir a pruebas para obtener la condición fija ni prestar servicios como personal estatutario temporal.", "Durante dos años solo puede prestar servicios temporales en otro servicio de salud.", "Durante seis meses no puede reingresar en la misma categoría, sin otros efectos."], "B", "La separación lleva una exclusión de seis años en los términos expresamente fijados por el artículo 73.1.a.", "Ley 55/2003, art. 73.1.a", 271, 272, "plazo_efecto"),

  q("SMS-T13-0107", "SMS-T13-C31", "absolute", "¿Qué efecto tiene una pena firme de inhabilitación absoluta sobre la condición de personal estatutario fijo?", ["Produce la pérdida de la condición.", "Solo impide la promoción interna durante seis años.", "Produce suspensión de funciones mientras dure la pena, pero conserva siempre la condición.", "Solo causa pérdida si su duración excede de seis años."], "A", "El artículo 25 atribuye a la inhabilitación absoluta firme la pérdida; el umbral de más de seis años corresponde a la inhabilitación especial para la profesión.", "Ley 55/2003, art. 25", 247, 247, "concepto_proximo"),
  q("SMS-T13-0108", "SMS-T13-C31", "special_public_employment", "Una sentencia firme impone inhabilitación especial para empleo o cargo público. ¿Cuándo determina la pérdida de la condición estatutaria conforme al artículo 25?", ["Siempre que la pena sea superior a dos años.", "Únicamente cuando afecte al correspondiente nombramiento.", "Solo cuando impida ejercer cualquier profesión sanitaria.", "Siempre, aunque no guarde relación alguna con el nombramiento."], "B", "La inhabilitación especial para empleo o cargo público produce pérdida cuando afecta al correspondiente nombramiento.", "Ley 55/2003, art. 25", 247, 247, "requisito"),
  q("SMS-T13-0109", "SMS-T13-C31", "boundary", "Se impone por sentencia firme una inhabilitación especial para la correspondiente profesión de exactamente seis años. Atendiendo al artículo 25, ¿produce por esa regla la pérdida de la condición?", ["Sí, porque seis años ya alcanzan el umbral legal.", "Sí, siempre que la inhabilitación sea profesional, cualquiera que sea su duración.", "No, esa causa exige que la inhabilitación especial para la profesión exceda de seis años.", "No, porque solo la inhabilitación absoluta puede causar pérdida."], "C", "El precepto utiliza «exceda de seis años»; exactamente seis no supera ese umbral.", "Ley 55/2003, art. 25", 247, 247, "literalidad_limite"),

  q("SMS-T13-0110", "SMS-T13-C06", "authorization_conditions", "Un profesional solicita prolongar voluntariamente el servicio activo después de la edad de jubilación forzosa. ¿Qué exige el artículo 26.2 además de no superar los 70 años?", ["Que acredite al menos treinta y cinco años de cotización y exista plaza vacante.", "Que conserve la capacidad funcional necesaria y que el servicio de salud autorice la prolongación según las necesidades de organización.", "Que haya obtenido previamente un nuevo nombramiento mediante concurso.", "Que la Comisión de Recursos Humanos del SNS autorice individualmente la prolongación."], "B", "La prolongación no es automática: exige capacidad funcional y autorización según las necesidades organizativas del servicio de salud.", "Ley 55/2003, art. 26.2", 247, 248, "combinacion_requisitos"),
  q("SMS-T13-0111", "SMS-T13-C06", "contribution_extension_end", "Si al alcanzar la edad de jubilación forzosa faltan seis años o menos de cotización para causar pensión, la prórroga prevista en el artículo 26.3:", ["Puede mantenerse necesariamente hasta los 70 años aunque antes se complete la cotización necesaria.", "Se extiende como máximo hasta completar el tiempo de cotización necesario para causar pensión, siempre que exista capacidad funcional.", "Solo puede durar seis meses y exige convocatoria pública.", "Convierte la jubilación forzosa en voluntaria sin límite temporal."], "B", "La prórroga dura solo el tiempo necesario para causar pensión y exige capacidad funcional; no se prolonga por encima de ese objetivo.", "Ley 55/2003, art. 26.3", 247, 248, "efecto_limite"),

  q("SMS-T13-0112", "SMS-T13-C32", "contrast_partial_temporary", "¿Cuál de estas situaciones NO figura en el artículo 27 como causa de pérdida de la condición estatutaria?", ["Incapacidad permanente total para la profesión habitual.", "Incapacidad permanente absoluta para todo trabajo.", "Gran invalidez reconocida conforme al régimen de Seguridad Social.", "Incapacidad temporal que impide transitoriamente prestar servicios."], "D", "El artículo 27 enumera total para la profesión habitual, absoluta y gran invalidez; la incapacidad temporal no es uno de esos grados extintivos.", "Ley 55/2003, art. 27", 248, 248, "concepto_proximo"),
  q("SMS-T13-0113", "SMS-T13-C32", "scope_total_vs_absolute", "¿Qué diferencia recoge correctamente el artículo 27 entre incapacidad permanente total y absoluta?", ["La total se refiere a la profesión habitual; la absoluta, a todo trabajo.", "La total se refiere a todo trabajo; la absoluta, únicamente al puesto concreto.", "Ambas se refieren exclusivamente a la plaza de destino.", "No existe diferencia de alcance: solo cambia la duración de la prestación."], "A", "La total se proyecta sobre la profesión habitual y la absoluta sobre todo trabajo.", "Ley 55/2003, art. 27", 248, 248, "contraste"),
  q("SMS-T13-0114", "SMS-T13-C32", "legal_effect", "Declarada una incapacidad permanente total para la profesión habitual en los términos del Régimen General de la Seguridad Social, ¿qué prevé el artículo 27?", ["La pérdida de la condición de personal estatutario.", "La reserva indefinida de plaza hasta una eventual revisión.", "La promoción automática a una categoría compatible.", "La excedencia voluntaria obligatoria sin pérdida de condición."], "A", "La incapacidad permanente total para la profesión habitual es una de las causas de pérdida del artículo 27.", "Ley 55/2003, art. 27", 248, 248, "efecto"),

  q("SMS-T13-0115", "SMS-T13-C07", "late_review_effect", "La incapacidad que causó la pérdida de la condición se revisa favorablemente transcurridos más de dos años desde su declaración. ¿Qué regla general resulta aplicable a la recuperación?", ["Existe derecho automático a la misma plaza concreta y turno anteriores.", "Se recupera la condición con declaración simultánea de excedencia voluntaria y posible reingreso por los procedimientos del artículo 69, sin permanencia mínima.", "Debe superarse necesariamente un nuevo proceso selectivo completo.", "La recuperación queda legalmente excluida una vez transcurridos dos años."], "B", "El derecho reforzado a misma categoría y área se reserva a revisión dentro de dos años; fuera de esa excepción opera la regla del artículo 28.3.", "Ley 55/2003, art. 28.2-3", 248, 249, "excepcion_temporal"),

  q("SMS-T13-0116", "SMS-T13-C08", "additional_principles", "Además de igualdad, mérito, capacidad y publicidad, ¿qué principio básico de provisión recoge expresamente el artículo 29.1?", ["La programación periódica de las convocatorias dentro de una planificación eficiente de recursos.", "La preferencia general del personal temporal sobre el fijo en movilidad.", "La libre designación como sistema ordinario de todas las plazas.", "La centralización estatal de todas las convocatorias de los servicios de salud."], "A", "El artículo 29.1 incluye planificación eficiente y programación periódica, junto con integración, movilidad, coordinación y participación negociada.", "Ley 55/2003, art. 29.1", 249, 250, "literalidad_catalogo"),
  q("SMS-T13-0117", "SMS-T13-C08", "free_designation_scope", "Respecto de la libre designación, el artículo 29.3 dispone que:", ["Todas las plazas directivas se cubren necesariamente por libre designación estatal.", "Cada servicio de salud determinará los puestos que puedan ser provistos mediante libre designación.", "Solo puede utilizarse para personal temporal y por un máximo de dos años.", "Sustituye a selección, promoción, movilidad y reingreso cuando exista urgencia."], "B", "La ley remite a cada servicio de salud la determinación de los puestos susceptibles de libre designación.", "Ley 55/2003, art. 29.3", 249, 250, "competencia"),

  q("SMS-T13-0118", "SMS-T13-C09", "test_function_fit", "¿Qué exige el artículo 30.2 respecto del contenido y las pruebas de los procedimientos de selección?", ["Que sean idénticos para todas las categorías del Sistema Nacional de Salud.", "Que se adecuen a las funciones a desarrollar en las plazas, incluida en su caso la acreditación de la lengua oficial conforme a la normativa autonómica.", "Que consistan siempre en concurso-oposición con fase práctica obligatoria.", "Que se limiten a valorar méritos previamente prestados en el mismo servicio de salud."], "B", "El artículo 30.2 exige adecuación de procedimientos, contenidos y pruebas a las funciones y contempla, cuando proceda, la lengua oficial.", "Ley 55/2003, art. 30.2", 250, 252, "requisito"),

  q("SMS-T13-0119", "SMS-T13-C12", "selection_body_members", "¿Qué requisito profesional exige el artículo 31.8 a los miembros de los órganos de selección?", ["Ser exclusivamente personal estatutario fijo del servicio convocante y de la misma categoría.", "Pertenecer a los tipos de personal admitidos por la ley y ocupar plaza o categoría con titulación de nivel académico igual o superior al exigido para el ingreso.", "Ser personal funcionario de carrera con al menos diez años de antigüedad.", "Ser designados por la Comisión de Recursos Humanos del SNS en todos los casos."], "B", "El artículo 31.8 admite funcionario de carrera, estatutario fijo o laboral de centros vinculados al SNS, con el nivel académico exigido.", "Ley 55/2003, art. 31.8", 252, 254, "requisitos_miembros"),
  q("SMS-T13-0120", "SMS-T13-C12", "appointment_content_publication", "Según el artículo 32, ¿qué afirmación sobre los nombramientos de personal estatutario fijo es correcta?", ["Se publican necesariamente en el BOE y no necesitan indicar ámbito.", "Se publican en la forma que determine cada servicio de salud y deben indicar expresamente el ámbito al que corresponden.", "Solo se notifican de forma individual y su ámbito puede fijarse después de la incorporación.", "Su publicación y ámbito quedan a elección del tribunal de selección."], "B", "Los apartados 2 y 3 del artículo 32 regulan publicación conforme a cada servicio y expresión del ámbito en el nombramiento.", "Ley 55/2003, art. 32.2-3", 254, 254, "contenido_formal"),

  q("SMS-T13-0121", "SMS-T13-C15", "negotiation", "Los procedimientos mediante los que se ofrece promoción interna temporal al personal estatutario fijo:", ["Deben ser objeto de negociación en las mesas correspondientes.", "Se aprueban unilateralmente por cada centro sin negociación posible.", "Requieren autorización individual de la Comisión de Recursos Humanos del SNS.", "Solo pueden establecerse por una ley estatal específica para cada categoría."], "A", "El artículo 35.1 establece expresamente que estos procedimientos serán objeto de negociación en las mesas correspondientes.", "Ley 55/2003, art. 35.1", 256, 257, "procedimiento"),

  q("SMS-T13-0122", "SMS-T13-C17", "trigger", "¿Cuándo opera específicamente la regla de coordinación y colaboración del artículo 38?", ["En toda convocatoria interna de un único centro sanitario.", "Cuando las convocatorias de provisión, selección o movilidad afecten a más de un servicio de salud.", "Solo cuando se trate de promoción interna temporal.", "Únicamente si la convocatoria incluye plazas de distintas comunidades autónomas y del Estado."], "B", "El presupuesto del artículo 38 es que la convocatoria afecte a más de un servicio de salud.", "Ley 55/2003, art. 38", 259, 259, "ambito_aplicacion"),
  q("SMS-T13-0123", "SMS-T13-C17", "principle", "En las convocatorias a las que se refiere el artículo 38 debe primar:", ["El principio de antigüedad del servicio convocante.", "El principio de colaboración entre todos los servicios de salud afectados.", "La autonomía absoluta de cada tribunal sin criterios comunes.", "La preferencia del servicio con mayor número de plazas."], "B", "La norma ordena que prime el principio de colaboración entre todos los servicios de salud.", "Ley 55/2003, art. 38", 259, 259, "principio"),
  q("SMS-T13-0124", "SMS-T13-C17", "scope_of_commission", "¿Sobre qué aspectos establece criterios y principios la Comisión de Recursos Humanos del SNS en el artículo 38?", ["Sobre cuantía retributiva y jornada individual de cada plaza.", "Sobre periodicidad y coordinación de las convocatorias afectadas.", "Sobre sanciones disciplinarias de los aspirantes.", "Sobre composición nominativa de cada órgano de selección."], "B", "La Comisión establece los criterios y principios procedentes en orden a la periodicidad y coordinación.", "Ley 55/2003, art. 38", 259, 259, "competencia_objeto"),

  q("SMS-T13-0125", "SMS-T13-C33", "eligibility_temporality", "Una plaza está temporalmente desatendida y se pretende cubrir en comisión de servicios. ¿Qué exige el artículo 39.1?", ["Que la cobertura sea definitiva y recaiga en personal de cualquier categoría.", "Que responda a necesidades del servicio, tenga carácter temporal y recaiga en personal estatutario de la correspondiente categoría y especialidad.", "Que exista siempre cambio de localidad y aceptación de una reducción retributiva.", "Que el puesto haya estado vacante durante al menos seis meses."], "B", "El artículo 39.1 exige necesidades del servicio, vacante o desatención temporal, carácter temporal y categoría/especialidad correspondiente.", "Ley 55/2003, art. 39.1", 259, 260, "combinacion_requisitos"),
  q("SMS-T13-0126", "SMS-T13-C33", "reservation", "¿Qué derecho mantiene quien se encuentra en comisión de servicios según el artículo 39.3?", ["La consolidación automática del puesto desempeñado al año.", "La reserva de su plaza o puesto de trabajo de origen.", "La percepción obligatoria del complemento de destino más alto de ambos puestos.", "La preferencia absoluta en cualquier movilidad posterior."], "B", "El artículo 39.3 reconoce expresamente la reserva de la plaza o puesto de origen.", "Ley 55/2003, art. 39.3", 259, 260, "efecto"),

  q("SMS-T13-0127", "SMS-T13-C18", "autonomous_implementation", "¿Quién establece los mecanismos de carrera profesional para el personal estatutario de sus servicios de salud conforme al artículo 40.1?", ["La Comisión de Recursos Humanos del SNS, sin negociación previa.", "Las comunidades autónomas, previa negociación en las mesas correspondientes.", "Cada centro sanitario de forma autónoma y sin marco general.", "El Ministerio de Sanidad mediante convocatorias anuales individuales."], "B", "El artículo 40.1 atribuye a las comunidades autónomas el establecimiento de mecanismos, previa negociación.", "Ley 55/2003, art. 40.1", 260, 261, "competencia"),
  q("SMS-T13-0128", "SMS-T13-C18", "adaptation_negotiation", "Los criterios generales de desarrollo profesional de la normativa de profesiones sanitarias, al proyectarse sobre la carrera del Estatuto Marco:", ["Se aplican de forma uniforme sin adaptación a cada servicio o centro.", "Se acomodan a las condiciones organizativas, sanitarias y asistenciales, y su repercusión en la carrera se negocia en las mesas correspondientes.", "Quedan excluidos de la carrera profesional estatutaria.", "Solo producen efectos retributivos si los aprueba individualmente la Comisión de Recursos Humanos."], "B", "El artículo 40.4 exige adaptación a las características del servicio/centro y negociación de su repercusión en carrera.", "Ley 55/2003, art. 40.4", 260, 261, "adaptacion"),

  q("SMS-T13-0129", "SMS-T13-C20", "salary_basis", "¿De qué depende el sueldo básico asignado a cada categoría según el artículo 42.1.a?", ["De la antigüedad individual acumulada en cualquier Administración.", "Del título exigido para el desempeño de la categoría.", "Del nivel del puesto concreto ocupado en cada centro.", "De la evaluación anual de productividad."], "B", "El sueldo se asigna a cada categoría en función del título exigido; antigüedad, puesto y productividad corresponden a otros conceptos.", "Ley 55/2003, art. 42.1.a", 262, 263, "concepto_proximo"),

  q("SMS-T13-0130", "SMS-T13-C21", "general_nature", "Con carácter general, las retribuciones complementarias del artículo 43:", ["Son siempre fijas y se determinan de forma idéntica en todos los servicios de salud.", "Pueden ser fijas o variables y retribuyen, entre otros factores, función, categoría, dedicación, actividad, productividad, objetivos y resultados.", "Se reducen exclusivamente a destino y específico.", "Solo pueden percibirse por personal con carrera profesional reconocida."], "B", "El artículo 43.1 define las complementarias como fijas o variables y enumera un conjunto amplio de factores retribuidos.", "Ley 55/2003, art. 43.1", 263, 263, "definicion"),

  q("SMS-T13-0131", "SMS-T13-C22", "temporary_scope", "Un nombramiento temporal tiene asociados sueldo, pagas extraordinarias y complementos de destino y productividad. Según el artículo 44, ¿qué regla retributiva se aplica?", ["Percibe solo sueldo y pagas extraordinarias, nunca complementos.", "Percibe las básicas y complementarias correspondientes al nombramiento, con excepción de los trienios.", "Percibe todas las retribuciones, incluidos trienios, desde el primer día.", "Percibe únicamente las complementarias variables y no las básicas."], "B", "El artículo 44 reconoce la totalidad de básicas y complementarias del nombramiento salvo trienios.", "Ley 55/2003, art. 44", 263, 264, "aplicacion"),
  q("SMS-T13-0132", "SMS-T13-C22", "practice_floor", "Al fijar la retribución de un aspirante en prácticas, un servicio de salud debe respetar como mínimo:", ["El sueldo de la categoría de procedencia más todos sus complementos.", "Las retribuciones básicas, excluidos trienios, del grupo al que aspire ingresar.", "Las retribuciones completas del puesto definitivo, incluidos trienios.", "El salario mínimo interprofesional, sin referencia al grupo de ingreso."], "B", "El artículo 45 permite fijación por cada servicio, pero establece ese mínimo legal ligado al grupo de ingreso.", "Ley 55/2003, art. 45", 264, 264, "minimo"),

  q("SMS-T13-0133", "SMS-T13-C25", "dies_a_quo", "¿Desde qué momento comienza a contarse el plazo de prescripción de una falta disciplinaria?", ["Desde la fecha en que la Administración conoce los hechos.", "Desde que la falta se hubiera cometido.", "Desde la notificación del acuerdo de iniciación.", "Desde la firmeza de la eventual sanción."], "B", "El artículo 72.6 fija como dies a quo la comisión de la falta.", "Ley 55/2003, art. 72.6", 267, 271, "dies_a_quo"),
  q("SMS-T13-0134", "SMS-T13-C25", "interruption_event", "¿Qué actuación interrumpe la prescripción de la falta conforme al artículo 72.6?", ["La mera apertura interna de diligencias, aunque no se comunique al interesado.", "La notificación del acuerdo de iniciación del procedimiento disciplinario.", "La propuesta de sanción, una vez finalizada la instrucción.", "La inscripción de la falta en el expediente personal."], "B", "La interrupción se produce desde la notificación del acuerdo de iniciación.", "Ley 55/2003, art. 72.6", 267, 271, "interrupcion"),

  q("SMS-T13-0135", "SMS-T13-C27", "periods", "¿Cuáles son los plazos de prescripción de las sanciones impuestas por faltas muy graves, graves y leves?", ["Cuatro años, dos años y seis meses, respectivamente.", "Seis años, cuatro años y dos años, respectivamente.", "Tres años, dos años y un año, respectivamente.", "Cuatro años, un año y seis meses, respectivamente."], "A", "El artículo 73.4 fija 4 años / 2 años / 6 meses según la gravedad de la falta sancionada.", "Ley 55/2003, art. 73.4", 271, 272, "plazo"),
  q("SMS-T13-0136", "SMS-T13-C27", "execution_interruption", "¿Qué hecho interrumpe la prescripción de una sanción ya impuesta?", ["La mera anotación de la sanción en el expediente personal.", "El inicio, con conocimiento del interesado, del procedimiento de ejecución de la sanción.", "La apertura del procedimiento disciplinario que originó la sanción.", "La solicitud de cancelación de la anotación por el interesado."], "B", "La prescripción de la sanción se interrumpe por el inicio del procedimiento de ejecución con conocimiento del interesado.", "Ley 55/2003, art. 73.4", 271, 272, "interrupcion"),
  q("SMS-T13-0137", "SMS-T13-C27", "boundary_six_months", "El procedimiento de ejecución de una sanción queda paralizado exactamente seis meses por causa no imputable al interesado. ¿Vuelve a correr por esa sola circunstancia el plazo de prescripción según el artículo 73.4?", ["Sí, porque seis meses exactos cumplen el umbral.", "Sí, pero únicamente para sanciones leves.", "No, la ley exige que la paralización sea superior a seis meses.", "No, una vez interrumpida la prescripción de una sanción nunca vuelve a correr."], "C", "El artículo 73.4 exige paralización superior a seis meses; seis meses exactos no exceden el umbral.", "Ley 55/2003, art. 73.4", 271, 272, "literalidad_limite"),

  q("SMS-T13-0138", "SMS-T13-C34", "ex_officio", "La cancelación de las anotaciones de sanciones disciplinarias, una vez cumplidos los plazos legales:", ["Se realiza de oficio.", "Requiere siempre solicitud expresa del interesado.", "Solo puede acordarla un órgano judicial.", "Opera únicamente si no existe ninguna sanción anterior."], "A", "El artículo 73.5 establece la cancelación de oficio tras los períodos correspondientes desde el cumplimiento.", "Ley 55/2003, art. 73.5", 271, 272, "competencia_procedimiento"),
  q("SMS-T13-0139", "SMS-T13-C34", "periods_from_fulfillment", "¿Qué secuencia corresponde a los plazos de cancelación de anotaciones desde el cumplimiento de la sanción?", ["Leve: 6 meses; grave: 2 años; muy grave: 4 años.", "Leve: 1 año; grave: 2 años; muy grave: 6 años.", "Leve: 6 meses; grave: 4 años; muy grave: 6 años.", "Leve: 2 años; grave: 4 años; muy grave: 6 años."], "A", "El artículo 73.5 fija 6 meses, 2 años y 4 años según sanción por falta leve, grave o muy grave.", "Ley 55/2003, art. 73.5", 271, 272, "plazo"),
  q("SMS-T13-0140", "SMS-T13-C34", "annotation_scope", "¿Qué sanciones deben anotarse en el expediente personal antes de que pueda operar posteriormente su cancelación?", ["Solo las sanciones por faltas muy graves.", "Las sanciones disciplinarias firmes que se impongan.", "Únicamente las sanciones que impliquen pérdida del destino.", "También las medidas provisionales aunque no exista sanción firme."], "B", "El artículo 73.5 ordena anotar las sanciones disciplinarias firmes; la cancelación posterior afecta a esas anotaciones.", "Ley 55/2003, art. 73.5", 271, 272, "requisito_firmeza"),

  q("SMS-T13-0141", "SMS-T13-C28", "procedure_principles", "¿A qué principios debe ajustarse el procedimiento disciplinario en todos los servicios de salud conforme al artículo 74.2?", ["Publicidad, libre concurrencia y eficiencia presupuestaria.", "Celeridad, inmediatez y economía procesal.", "Jerarquía, descentralización y desconcentración.", "Oralidad, gratuidad y doble instancia."], "B", "El artículo 74.2 enuncia expresamente celeridad, inmediatez y economía procesal.", "Ley 55/2003, art. 74.2", 272, 274, "principios"),
  q("SMS-T13-0142", "SMS-T13-C28", "rights", "Durante un procedimiento disciplinario, ¿cuál de estas facultades está expresamente garantizada al interesado?", ["Formular alegaciones únicamente antes del nombramiento de instructor.", "Proponer cuantas pruebas sean adecuadas para determinar los hechos y formular alegaciones en cualquier fase.", "Elegir libremente al instructor y al secretario del expediente.", "Suspender unilateralmente la tramitación mientras busca asistencia letrada."], "B", "El artículo 74.2 reconoce alegaciones en cualquier fase y propuesta de pruebas adecuadas, además de otras garantías.", "Ley 55/2003, art. 74.2.d-e", 272, 274, "garantias"),

  q("SMS-T13-0143", "SMS-T13-C29", "judicial_duration", "Si se acuerda suspensión provisional tras auto de procesamiento o de apertura de juicio oral, ¿cuál puede ser su duración máxima según el artículo 75.3?", ["Seis meses en todo caso, sin excepción.", "Hasta la resolución del procedimiento judicial.", "Dos años, coincidiendo con la sanción máxima por falta grave.", "Hasta la propuesta de resolución del expediente disciplinario."], "B", "En el supuesto judicial del artículo 75.3, la medida puede extenderse como máximo hasta la resolución del procedimiento.", "Ley 55/2003, art. 75.3", 274, 275, "duracion_excepcion"),
  q("SMS-T13-0144", "SMS-T13-C29", "judicial_no_pay", "Una medida judicial impide al personal estatutario desempeñar sus funciones durante más de cinco días consecutivos. ¿Qué prevé el artículo 75.4 mientras dure esa situación?", ["Suspensión provisional con derecho a todas las retribuciones complementarias.", "Suspensión provisional sin derecho a percepción de retribuciones.", "Separación automática del servicio desde el sexto día.", "Excedencia voluntaria con reserva de plaza y sueldo básico."], "B", "El artículo 75.4 prevé suspensión provisional sin retribuciones cuando prisión provisional u otras medidas judiciales impiden trabajar más de cinco días consecutivos.", "Ley 55/2003, art. 75.4", 274, 275, "efecto_excepcion"),
] as const;
