import type {
  FactoryEvidenceDimension,
  FactoryGeneratedQuestionCandidate,
  V2QuestionRow,
} from "../types";

const MATERIA =
  "Ley 39/2015, de 1 de octubre, del Procedimiento Administrativo Común de las Administraciones Públicas";
const TEMA =
  "La Ley 39/2015, de 1 de octubre, del Procedimiento Administrativo Común de las Administraciones Públicas (I). La actividad de las Administraciones Públicas: normas generales de actuación; términos y plazos. Los actos administrativos.";

function row(input: {
  code: string;
  apartado: string;
  subapartado: string;
  concepto: string;
  objetivo: string;
  perspectiva: string;
  nivel: "aprendizaje" | "consolidacion" | "tribunal";
  dificultadConceptual: "facil" | "medio" | "dificil";
  dificultadExamen: "facil" | "medio" | "dificil";
  trampa: string;
  pregunta: string;
  a: string;
  b: string;
  c: string;
  d: string;
  correcta: "A" | "B" | "C" | "D";
  explicacion: string;
  pageStart: number;
  pageEnd?: number;
  referencia: string;
}): V2QuestionRow {
  return {
    codigo: input.code,
    materia: MATERIA,
    numero_tema: 18,
    tema: TEMA,
    apartado: input.apartado,
    subapartado: input.subapartado,
    concepto: input.concepto,
    objetivo_aprendizaje: input.objetivo,
    perspectiva: input.perspectiva,
    nivel_pedagogico: input.nivel,
    dificultad_conceptual: input.dificultadConceptual,
    dificultad_examen: input.dificultadExamen,
    tipo_trampa: input.trampa,
    pregunta: input.pregunta,
    opcion_a: input.a,
    opcion_b: input.b,
    opcion_c: input.c,
    opcion_d: input.d,
    respuesta_correcta: input.correcta,
    explicacion: input.explicacion,
    documento_referencia: "Temario_new.pdf",
    pagina_inicio: input.pageStart,
    pagina_fin: input.pageEnd ?? input.pageStart,
    referencia_fuente: input.referencia,
    frecuencia_historica: "no_determinada",
  };
}

function candidate(
  conceptCode: string,
  dimension: FactoryEvidenceDimension,
  v2: V2QuestionRow,
): FactoryGeneratedQuestionCandidate {
  return { conceptCode, dimensions: [dimension], v2 };
}

/**
 * Governance-approved directed generation for Topic 18.
 *
 * Only concepts with a Gate 1 coverage gap are eligible. Every substantive
 * statement is grounded in Temario_new.pdf. C29 is deliberately absent: its
 * three planned slots are blocked below instead of manufacturing paraphrases.
 */
export const topic18GapQuestionCandidates: FactoryGeneratedQuestionCandidate[] = [
  candidate(
    "SMS-T18-C01",
    "subject",
    row({
      code: "SMS-T18-0241",
      apartado: "Actividad de las Administraciones Públicas",
      subapartado: "Normas generales de actuación",
      concepto: "Derechos de las personas ante las Administraciones",
      objetivo: "Identificar a quién atribuye el artículo 13 la titularidad de los derechos generales frente a las Administraciones Públicas.",
      perspectiva: "requisitos",
      nivel: "consolidacion",
      dificultadConceptual: "medio",
      dificultadExamen: "medio",
      trampa: "concepto_proximo",
      pregunta: "Según el artículo 13 reproducido en el temario, ¿quiénes son titulares de los derechos que enumera en sus relaciones con las Administraciones Públicas?",
      a: "Exclusivamente quienes ya tengan la condición de interesados en un procedimiento administrativo.",
      b: "Quienes, de conformidad con el artículo 3, tengan capacidad de obrar ante las Administraciones Públicas.",
      c: "Únicamente quienes estén obligados a relacionarse con la Administración por medios electrónicos.",
      d: "Solo quienes comparezcan ante la Administración por medio de un representante debidamente acreditado.",
      correcta: "B",
      explicacion: "El artículo 13 abre el catálogo atribuyéndolo a quienes, de conformidad con el artículo 3, tienen capacidad de obrar ante las Administraciones Públicas. No lo limita a interesados, obligados electrónicos ni representados.",
      pageStart: 113,
      pageEnd: 114,
      referencia: "Temario_new.pdf, art. 13, pp. 113-114.",
    }),
  ),
  candidate(
    "SMS-T18-C25",
    "competence",
    row({
      code: "SMS-T18-0242",
      apartado: "Actos administrativos",
      subapartado: "Requisitos de los actos administrativos",
      concepto: "Producción y contenido de los actos",
      objetivo: "Precisar la exigencia de competencia del órgano productor del acto con independencia de la forma de iniciación.",
      perspectiva: "requisitos",
      nivel: "consolidacion",
      dificultadConceptual: "medio",
      dificultadExamen: "medio",
      trampa: "competencia",
      pregunta: "Un procedimiento se inicia a solicitud del interesado. Conforme al artículo 34.1, para producir el acto administrativo correspondiente se exige que:",
      a: "Lo dicte el órgano competente, ajustándose a los requisitos y al procedimiento establecido.",
      b: "Lo dicte necesariamente un órgano superior al que haya tramitado la solicitud del interesado.",
      c: "Lo dicte el órgano que recibió la solicitud, aunque la competencia corresponda a otro órgano.",
      d: "La competencia del órgano solo sea exigible cuando el procedimiento se hubiera iniciado de oficio.",
      correcta: "A",
      explicacion: "El artículo 34.1 exige que los actos, tanto de oficio como a instancia del interesado, se produzcan por el órgano competente y se ajusten a los requisitos y al procedimiento establecido.",
      pageStart: 136,
      referencia: "Temario_new.pdf, art. 34.1, p. 136.",
    }),
  ),
  candidate(
    "SMS-T18-C25",
    "mini_case",
    row({
      code: "SMS-T18-0243",
      apartado: "Actos administrativos",
      subapartado: "Requisitos de los actos administrativos",
      concepto: "Producción y contenido de los actos",
      objetivo: "Aplicar conjuntamente competencia y sujeción a los requisitos y al procedimiento del artículo 34.1.",
      perspectiva: "caso_practico",
      nivel: "tribunal",
      dificultadConceptual: "medio",
      dificultadExamen: "dificil",
      trampa: "combinada",
      pregunta: "Un órgano competente dicta un acto cuyo contenido es determinado y adecuado a sus fines, pero omite un requisito establecido para su producción. Atendiendo solo al artículo 34 del temario, ¿qué conclusión es correcta?",
      a: "Cumple el artículo 34 porque la competencia del órgano basta para considerar correctamente producido el acto.",
      b: "Cumple el artículo 34 porque la determinación y adecuación del contenido sustituyen cualquier requisito procedimental.",
      c: "Cumple el artículo 34 siempre que la omisión pueda ponerse en conocimiento del interesado al notificar el acto.",
      d: "No satisface el artículo 34.1, que exige además ajustar la producción del acto a los requisitos y al procedimiento establecido.",
      correcta: "D",
      explicacion: "La competencia no agota el artículo 34.1: la producción del acto debe ajustarse también a los requisitos y al procedimiento establecido. Las exigencias materiales del apartado 2 no sustituyen esa regla.",
      pageStart: 136,
      referencia: "Temario_new.pdf, art. 34.1-2, p. 136.",
    }),
  ),
  candidate(
    "SMS-T18-C28",
    "literal",
    row({
      code: "SMS-T18-0244",
      apartado: "Actos administrativos",
      subapartado: "Requisitos de los actos administrativos",
      concepto: "Inderogabilidad singular",
      objetivo: "Reconocer la segunda causa de nulidad que el artículo 37.2 incorpora por remisión al artículo 47.",
      perspectiva: "afirmacion_correcta",
      nivel: "consolidacion",
      dificultadConceptual: "medio",
      dificultadExamen: "medio",
      trampa: "omision",
      pregunta: "Además de las resoluciones administrativas que vulneren una disposición reglamentaria, el artículo 37.2 declara nulas las resoluciones que:",
      a: "Tengan su eficacia demorada por estar supeditadas a una notificación o publicación posterior.",
      b: "Se dicten fuera del tiempo establecido, cualquiera que sea la naturaleza del término o del plazo.",
      c: "Incurran en alguna de las causas de nulidad de pleno derecho recogidas en el artículo 47.",
      d: "Deban ser motivadas por haberse dictado en el ejercicio de una potestad discrecional.",
      correcta: "C",
      explicacion: "El artículo 37.2 contiene dos referencias: son nulas las resoluciones que vulneren una disposición reglamentaria y también las que incurran en alguna de las causas del artículo 47.",
      pageStart: 139,
      referencia: "Temario_new.pdf, art. 37.2, p. 139.",
    }),
  ),
  candidate(
    "SMS-T18-C31",
    "requirement",
    row({
      code: "SMS-T18-0248",
      apartado: "Actos administrativos",
      subapartado: "Eficacia de los actos",
      concepto: "Efectos en otras Administraciones y actuaciones de ejecución",
      objetivo: "Identificar el presupuesto que activa el mecanismo del artículo 39.5 frente al acto de otra Administración.",
      perspectiva: "requisitos",
      nivel: "tribunal",
      dificultadConceptual: "dificil",
      dificultadExamen: "dificil",
      trampa: "requisito",
      pregunta: "Una Administración considera ilegal un acto dictado por otra. Para que opere el mecanismo específico del artículo 39.5, el acto que la primera deba dictar:",
      a: "Debe publicarse necesariamente en el mismo diario oficial que el acto de la otra Administración.",
      b: "Debe proceder de un órgano jerárquicamente superior al órgano que dictó el acto considerado ilegal.",
      c: "Puede guardar una relación meramente incidental con el acto considerado ilegal, aunque no dependa de él.",
      d: "Debe tener necesariamente como base el acto de la otra Administración que considera ilegal.",
      correcta: "D",
      explicacion: "El artículo 39.5 parte de que una Administración haya de dictar un acto que tenga necesariamente por base otro dictado por una Administración distinta y que considere ilegal.",
      pageStart: 140,
      referencia: "Temario_new.pdf, art. 39.5, p. 140.",
    }),
  ),
  candidate(
    "SMS-T18-C34",
    "effect",
    row({
      code: "SMS-T18-0249",
      apartado: "Actos administrativos",
      subapartado: "Eficacia de los actos",
      concepto: "Notificaciones en papel",
      objetivo: "Reconocer la disponibilidad electrónica adicional exigida para las notificaciones practicadas en papel.",
      perspectiva: "efectos",
      nivel: "consolidacion",
      dificultadConceptual: "medio",
      dificultadExamen: "medio",
      trampa: "omision",
      pregunta: "Cuando una notificación se practique en papel, el artículo 42.1 dispone además que:",
      a: "Deberá ponerse a disposición del interesado en la sede electrónica para que pueda acceder voluntariamente a su contenido.",
      b: "La puesta a disposición electrónica sustituirá al intento en papel desde el mismo momento en que se genere la notificación.",
      c: "El interesado deberá aceptar previamente la vía electrónica para que el intento de notificación en papel pueda considerarse válido.",
      d: "La notificación solo se pondrá a disposición electrónica cuando haya resultado infructuoso un segundo intento en el domicilio.",
      correcta: "A",
      explicacion: "El artículo 42.1 mantiene la práctica en papel y añade que todas esas notificaciones deberán ponerse a disposición del interesado en la sede electrónica para acceso voluntario.",
      pageStart: 143,
      referencia: "Temario_new.pdf, art. 42.1, p. 143.",
    }),
  ),
  candidate(
    "SMS-T18-C35",
    "requirement",
    row({
      code: "SMS-T18-0250",
      apartado: "Actos administrativos",
      subapartado: "Eficacia de los actos",
      concepto: "Notificaciones electrónicas",
      objetivo: "Precisar qué actuación satisface la obligación de puesta a disposición prevista en el artículo 40.4.",
      perspectiva: "relacion_normativa",
      nivel: "consolidacion",
      dificultadConceptual: "medio",
      dificultadExamen: "medio",
      trampa: "concepto_proximo",
      pregunta: "Según el artículo 43.3, la obligación a la que se refiere el artículo 40.4 se entiende cumplida con:",
      a: "El envío de un aviso al dispositivo o correo electrónico comunicado, aunque la notificación aún no esté disponible.",
      b: "La puesta a disposición de la notificación en la sede electrónica o en la dirección electrónica habilitada única.",
      c: "La publicación del contenido íntegro del acto en el diario oficial correspondiente a la Administración actuante.",
      d: "El acceso efectivo del interesado o de su representante debidamente identificado al contenido de la notificación.",
      correcta: "B",
      explicacion: "El artículo 43.3 considera cumplida esa obligación con la puesta a disposición en la sede electrónica de la Administración u Organismo actuante o en la dirección electrónica habilitada única.",
      pageStart: 144,
      referencia: "Temario_new.pdf, art. 43.3, p. 144.",
    }),
  ),
  candidate(
    "SMS-T18-C36",
    "contrast",
    row({
      code: "SMS-T18-0251",
      apartado: "Actos administrativos",
      subapartado: "Eficacia de los actos",
      concepto: "Notificación infructuosa",
      objetivo: "Distinguir los medios complementarios de difusión de la publicación obligatoria del anuncio en el BOE.",
      perspectiva: "comparacion",
      nivel: "tribunal",
      dificultadConceptual: "medio",
      dificultadExamen: "dificil",
      trampa: "absolutismo",
      pregunta: "En un supuesto del artículo 44, una Administración establece una forma complementaria de notificación a través de otro medio de difusión. Esa actuación:",
      a: "Sustituye el anuncio en el BOE si permite acreditar que el interesado tuvo conocimiento del acto.",
      b: "Convierte el anuncio en el BOE en facultativo cuando el medio complementario sea de carácter electrónico.",
      c: "No excluye la obligación de publicar el correspondiente anuncio en el BOE.",
      d: "Solo puede utilizarse después de que transcurran diez días naturales sin acceso a una notificación electrónica.",
      correcta: "C",
      explicacion: "El artículo 44 permite otras formas complementarias de notificación, pero dice expresamente que no excluirán la obligación de publicar el correspondiente anuncio en el BOE.",
      pageStart: 145,
      referencia: "Temario_new.pdf, art. 44, p. 145.",
    }),
  ),
  candidate(
    "SMS-T18-C36",
    "literal",
    row({
      code: "SMS-T18-0252",
      apartado: "Actos administrativos",
      subapartado: "Eficacia de los actos",
      concepto: "Notificación infructuosa",
      objetivo: "Reconocer los lugares de publicación previa facultativa expresamente enumerados por el artículo 44.",
      perspectiva: "reconocimiento_directo",
      nivel: "consolidacion",
      dificultadConceptual: "medio",
      dificultadExamen: "medio",
      trampa: "omision",
      pregunta: "Antes del anuncio obligatorio en el BOE, ¿qué conjunto de medios contempla expresamente el artículo 44 con carácter facultativo?",
      a: "El boletín oficial autonómico o provincial, el tablón de edictos del último domicilio y el Consulado o Sección Consular correspondiente.",
      b: "La sede electrónica, la dirección electrónica habilitada única y el Punto de Acceso General de la Administración.",
      c: "El diario oficial de la Administración autora, cualquier registro electrónico y la oficina de asistencia más próxima al domicilio.",
      d: "El domicilio del interesado, el tablón de cualquier municipio y la sede electrónica de la Administración que tramite el expediente.",
      correcta: "A",
      explicacion: "El artículo 44 permite, previamente y de forma facultativa, publicar en el boletín oficial de la Comunidad Autónoma o Provincia, en el tablón de edictos del Ayuntamiento del último domicilio o en el Consulado o Sección Consular de la Embajada correspondiente.",
      pageStart: 145,
      referencia: "Temario_new.pdf, art. 44, p. 145.",
    }),
  ),
  candidate(
    "SMS-T18-C38",
    "competence",
    row({
      code: "SMS-T18-0253",
      apartado: "Actos administrativos",
      subapartado: "Eficacia de los actos",
      concepto: "Protección en notificaciones y publicaciones",
      objetivo: "Identificar quién aprecia la lesión que activa la limitación protectora de publicidad del artículo 46.",
      perspectiva: "competencia",
      nivel: "consolidacion",
      dificultadConceptual: "medio",
      dificultadExamen: "medio",
      trampa: "competencia",
      pregunta: "¿A quién atribuye el artículo 46 la apreciación de que una notificación por anuncios o la publicación de un acto lesiona derechos o intereses legítimos?",
      a: "Al interesado afectado, cuya alegación obliga por sí sola a sustituir la publicación prevista.",
      b: "Al órgano encargado materialmente de editar el diario oficial en el que vaya a publicarse el anuncio.",
      c: "Al órgano que hubiera aprobado la disposición general reguladora del procedimiento correspondiente.",
      d: "Al órgano competente, que en ese caso limita el contenido publicado en los términos del propio artículo.",
      correcta: "D",
      explicacion: "El artículo 46 comienza condicionando la medida a que el órgano competente aprecie que la notificación por anuncios o la publicación lesiona derechos o intereses legítimos.",
      pageStart: 146,
      referencia: "Temario_new.pdf, art. 46, p. 146.",
    }),
  ),
  candidate(
    "SMS-T18-C38",
    "effect",
    row({
      code: "SMS-T18-0254",
      apartado: "Actos administrativos",
      subapartado: "Eficacia de los actos",
      concepto: "Protección en notificaciones y publicaciones",
      objetivo: "Precisar la finalidad de la comparecencia indicada en la publicación limitada del artículo 46.",
      perspectiva: "efectos",
      nivel: "tribunal",
      dificultadConceptual: "medio",
      dificultadExamen: "dificil",
      trampa: "omision",
      pregunta: "En la publicación limitada del artículo 46 se indica un lugar y un plazo para que los interesados comparezcan. ¿Qué finalidad atribuye el temario a esa comparecencia?",
      a: "Formular el recurso procedente y obtener por ese solo hecho la suspensión de la eficacia del acto publicado.",
      b: "Conocer el contenido íntegro del acto y dejar constancia de dicho conocimiento.",
      c: "Elegir el diario oficial en el que deba realizarse posteriormente la publicación íntegra del acto.",
      d: "Solicitar que la publicación sea sustituida necesariamente por una notificación practicada por medios electrónicos.",
      correcta: "B",
      explicacion: "La indicación debe señalar dónde pueden comparecer, dentro del plazo establecido, para conocer el contenido íntegro del acto y para que quede constancia de ese conocimiento.",
      pageStart: 146,
      referencia: "Temario_new.pdf, art. 46, p. 146.",
    }),
  ),
  candidate(
    "SMS-T18-C40",
    "mini_case",
    row({
      code: "SMS-T18-0255",
      apartado: "Actos administrativos",
      subapartado: "Nulidad y anulabilidad",
      concepto: "Anulabilidad",
      objetivo: "Aplicar la regla general de anulabilidad del artículo 48.1 a una infracción no encuadrada en nulidad de pleno derecho.",
      perspectiva: "caso_practico",
      nivel: "tribunal",
      dificultadConceptual: "medio",
      dificultadExamen: "dificil",
      trampa: "concepto_proximo",
      pregunta: "Un acto administrativo incurre en una infracción del ordenamiento jurídico y el supuesto no se plantea como una causa de nulidad de pleno derecho ni como un defecto especial de forma o de plazo. Según la regla general del artículo 48.1, el acto es:",
      a: "Nulo de pleno derecho por el mero hecho de existir cualquier infracción del ordenamiento jurídico.",
      b: "Plenamente válido porque las infracciones del ordenamiento solo afectan a actos dictados fuera de plazo.",
      c: "Anulable, pues el artículo 48.1 comprende cualquier infracción del ordenamiento jurídico, incluida la desviación de poder.",
      d: "Convertible automáticamente en otro acto distinto sin necesidad de que reúna sus elementos constitutivos.",
      correcta: "C",
      explicacion: "El artículo 48.1 establece como regla de anulabilidad que los actos de la Administración incurran en cualquier infracción del ordenamiento jurídico, incluso la desviación de poder.",
      pageStart: 147,
      referencia: "Temario_new.pdf, art. 48.1, p. 147.",
    }),
  ),
  candidate(
    "SMS-T18-C41",
    "mini_case",
    row({
      code: "SMS-T18-0256",
      apartado: "Actos administrativos",
      subapartado: "Nulidad y anulabilidad",
      concepto: "Límites a la extensión de la invalidez",
      objetivo: "Aplicar el límite del artículo 49.1 a un acto sucesivo independiente del acto inválido.",
      perspectiva: "caso_practico",
      nivel: "consolidacion",
      dificultadConceptual: "medio",
      dificultadExamen: "medio",
      trampa: "absolutismo",
      pregunta: "En un procedimiento se anula un acto y existe después otro acto sucesivo cuyo contenido es independiente del primero. Conforme al artículo 49.1:",
      a: "La anulabilidad del primero no implica por sí sola la del acto sucesivo independiente.",
      b: "El acto sucesivo independiente pasa a ser nulo de pleno derecho desde la anulación del primero.",
      c: "El acto sucesivo independiente debe convalidarse antes de poder conservar cualquier efecto.",
      d: "La invalidez se extiende siempre a todos los actos sucesivos, aunque sean independientes del primero.",
      correcta: "A",
      explicacion: "El artículo 49.1 limita la propagación de la invalidez: la nulidad o anulabilidad de un acto no implica la de los sucesivos en el procedimiento que sean independientes del primero.",
      pageStart: 148,
      referencia: "Temario_new.pdf, art. 49.1, p. 148.",
    }),
  ),
  candidate(
    "SMS-T18-C41",
    "literal",
    row({
      code: "SMS-T18-0257",
      apartado: "Actos administrativos",
      subapartado: "Nulidad y anulabilidad",
      concepto: "Límites a la extensión de la invalidez",
      objetivo: "Distinguir la regla de invalidez parcial y su excepción por el carácter determinante de la parte viciada.",
      perspectiva: "cambio_condicion",
      nivel: "tribunal",
      dificultadConceptual: "dificil",
      dificultadExamen: "dificil",
      trampa: "excepcion",
      pregunta: "La nulidad o anulabilidad de una parte de un acto, respecto de las partes independientes de aquella, produce como regla que:",
      a: "Todas las partes del acto quedan invalidadas por la sola existencia de una parte viciada.",
      b: "Solo se conservan las partes del acto que sean anteriores en el tiempo a la parte declarada inválida.",
      c: "Las partes independientes necesitan convalidación expresa para no quedar afectadas por la invalidez parcial.",
      d: "No quedan afectadas, salvo que la parte viciada sea de tal importancia que sin ella el acto no se hubiera dictado.",
      correcta: "D",
      explicacion: "El artículo 49.2 conserva las partes independientes del acto, con la excepción de que la parte viciada sea tan importante que sin ella el acto administrativo no se hubiera dictado.",
      pageStart: 148,
      referencia: "Temario_new.pdf, art. 49.2, p. 148.",
    }),
  ),
  candidate(
    "SMS-T18-C42",
    "subject",
    row({
      code: "SMS-T18-0258",
      apartado: "Actos administrativos",
      subapartado: "Nulidad y anulabilidad",
      concepto: "Conversión de actos viciados",
      objetivo: "Identificar qué clases de actos viciados contempla expresamente el artículo 50 para la conversión.",
      perspectiva: "clasificacion",
      nivel: "aprendizaje",
      dificultadConceptual: "facil",
      dificultadExamen: "medio",
      trampa: "concepto_proximo",
      pregunta: "¿Qué actos contempla expresamente el artículo 50 como posibles actos de partida de una conversión?",
      a: "Únicamente los actos anulables, porque un acto nulo nunca puede contener elementos aprovechables de otro.",
      b: "Únicamente los actos nulos de pleno derecho, porque la conversión sustituye a la anulabilidad.",
      c: "Los actos nulos o anulables que contengan los elementos constitutivos de otro acto distinto.",
      d: "Los actos válidos cuya eficacia esté demorada exclusivamente por falta de notificación o publicación.",
      correcta: "C",
      explicacion: "El artículo 50 se refiere expresamente a los actos nulos o anulables y condiciona la conversión a que contengan los elementos constitutivos de otro distinto.",
      pageStart: 148,
      referencia: "Temario_new.pdf, art. 50, p. 148.",
    }),
  ),
  candidate(
    "SMS-T18-C42",
    "requirement",
    row({
      code: "SMS-T18-0259",
      apartado: "Actos administrativos",
      subapartado: "Nulidad y anulabilidad",
      concepto: "Conversión de actos viciados",
      objetivo: "Aislar el requisito material que permite la conversión prevista por el artículo 50.",
      perspectiva: "requisitos",
      nivel: "consolidacion",
      dificultadConceptual: "medio",
      dificultadExamen: "medio",
      trampa: "requisito",
      pregunta: "Para que opere la conversión del artículo 50, el acto nulo o anulable debe:",
      a: "Haber sido dictado por el mismo órgano que sería competente para convalidar cualquier defecto del acto originario.",
      b: "Contener los elementos constitutivos de otro acto distinto.",
      c: "Haber mantenido íntegramente sus efectos hasta que se declare formalmente la nulidad o la anulabilidad.",
      d: "Presentar únicamente un defecto de forma que no provoque indefensión ni afecte a su finalidad.",
      correcta: "B",
      explicacion: "La condición que enuncia el artículo 50 es que el acto viciado contenga los elementos constitutivos de otro acto distinto; solo entonces se atribuyen los efectos de ese otro acto.",
      pageStart: 148,
      referencia: "Temario_new.pdf, art. 50, p. 148.",
    }),
  ),
  candidate(
    "SMS-T18-C42",
    "effect",
    row({
      code: "SMS-T18-0260",
      apartado: "Actos administrativos",
      subapartado: "Nulidad y anulabilidad",
      concepto: "Conversión de actos viciados",
      objetivo: "Precisar el efecto jurídico que el artículo 50 atribuye al acto convertido.",
      perspectiva: "consecuencia_juridica",
      nivel: "consolidacion",
      dificultadConceptual: "medio",
      dificultadExamen: "medio",
      trampa: "efecto",
      pregunta: "Si concurren los requisitos de conversión del artículo 50, el acto nulo o anulable:",
      a: "Producirá los efectos del acto distinto cuyos elementos constitutivos contiene.",
      b: "Permanecerá sin efecto hasta que se convalide el mismo acto originario.",
      c: "Conservará únicamente los trámites del procedimiento anteriores a la infracción.",
      d: "Recuperará automáticamente la validez del acto originario con efectos retroactivos.",
      correcta: "A",
      explicacion: "El efecto literal de la conversión es que el acto viciado que reúne los elementos constitutivos de otro distinto produce los efectos de este último.",
      pageStart: 148,
      referencia: "Temario_new.pdf, art. 50, p. 148.",
    }),
  ),
  candidate(
    "SMS-T18-C43",
    "competence",
    row({
      code: "SMS-T18-0261",
      apartado: "Actos administrativos",
      subapartado: "Nulidad y anulabilidad",
      concepto: "Conservación de actos y trámites",
      objetivo: "Identificar el órgano al que el artículo 51 atribuye el deber de conservación.",
      perspectiva: "competencia",
      nivel: "aprendizaje",
      dificultadConceptual: "facil",
      dificultadExamen: "medio",
      trampa: "competencia",
      pregunta: "¿Qué órgano debe disponer la conservación prevista en el artículo 51?",
      a: "El órgano que dictó el acto originario, aunque no sea quien declare la nulidad ni anule las actuaciones.",
      b: "El interesado, mediante una solicitud de conservación dirigida al órgano que tramite el procedimiento.",
      c: "El órgano que declare la nulidad o anule las actuaciones.",
      d: "Cualquier órgano jerárquicamente superior al que haya intervenido en el procedimiento afectado.",
      correcta: "C",
      explicacion: "El artículo 51 atribuye expresamente la decisión al órgano que declare la nulidad o anule las actuaciones.",
      pageStart: 148,
      referencia: "Temario_new.pdf, art. 51, p. 148.",
    }),
  ),
  candidate(
    "SMS-T18-C43",
    "requirement",
    row({
      code: "SMS-T18-0262",
      apartado: "Actos administrativos",
      subapartado: "Nulidad y anulabilidad",
      concepto: "Conservación de actos y trámites",
      objetivo: "Precisar la condición material que determina qué actos y trámites deben conservarse conforme al artículo 51.",
      perspectiva: "requisitos",
      nivel: "consolidacion",
      dificultadConceptual: "medio",
      dificultadExamen: "medio",
      trampa: "requisito",
      pregunta: "Tras declarar la nulidad o anular actuaciones, el artículo 51 ordena conservar aquellos actos y trámites:",
      a: "Que sean anteriores a la infracción, con independencia de si su contenido habría cambiado sin ella.",
      b: "Que ya hayan sido notificados al interesado antes de que se declare la invalidez de las actuaciones.",
      c: "Que hayan sido aceptados expresamente por todos los interesados personados en el procedimiento.",
      d: "Cuyo contenido se hubiera mantenido igual de no haberse cometido la infracción.",
      correcta: "D",
      explicacion: "La condición del artículo 51 es material: se conservan los actos y trámites cuyo contenido habría permanecido igual si no se hubiera cometido la infracción.",
      pageStart: 148,
      referencia: "Temario_new.pdf, art. 51, p. 148.",
    }),
  ),
  candidate(
    "SMS-T18-C43",
    "effect",
    row({
      code: "SMS-T18-0263",
      apartado: "Actos administrativos",
      subapartado: "Nulidad y anulabilidad",
      concepto: "Conservación de actos y trámites",
      objetivo: "Reconocer el carácter obligatorio de la conservación cuando se cumple la condición del artículo 51.",
      perspectiva: "afirmacion_correcta",
      nivel: "aprendizaje",
      dificultadConceptual: "facil",
      dificultadExamen: "medio",
      trampa: "absolutismo",
      pregunta: "Cuando un acto o trámite cumple la condición material del artículo 51, el órgano que declara la nulidad o anula las actuaciones:",
      a: "Puede conservarlo únicamente si la infracción que originó la invalidez era un defecto de forma.",
      b: "Dispondrá siempre su conservación, porque su contenido se habría mantenido igual sin la infracción.",
      c: "Debe convalidarlo antes de poder conservarlo dentro del procedimiento afectado.",
      d: "Solo puede conservarlo si se trata de un acto sucesivo independiente en el sentido del artículo 49.1.",
      correcta: "B",
      explicacion: "El artículo 51 utiliza una regla imperativa: el órgano dispondrá siempre la conservación de los actos y trámites cuyo contenido se hubiera mantenido igual sin la infracción.",
      pageStart: 148,
      referencia: "Temario_new.pdf, art. 51, p. 148.",
    }),
  ),
];

export type Topic18SourceReviewRequiredSlot = {
  questionCode: string;
  conceptCode: "SMS-T18-C29";
  status: "source_review_required";
  sourceReference: string;
  reason: string;
};

/**
 * Mathematical coverage requests three more C29 primaries after moving 0239 to
 * C30. Temario_new.pdf art. 38 contains only the single executivity sentence,
 * already directly tested by SMS-T18-0199. Producing three more would require
 * paraphrasing that same rule or importing implications from outside the source.
 */
export const topic18SourceReviewRequiredSlots: Topic18SourceReviewRequiredSlot[] = [
  "SMS-T18-0245",
  "SMS-T18-0246",
  "SMS-T18-0247",
].map((questionCode) => ({
  questionCode,
  conceptCode: "SMS-T18-C29" as const,
  status: "source_review_required" as const,
  sourceReference: "Temario_new.pdf, art. 38, p. 139.",
  reason:
    "El artículo 38 del temario contiene una única regla breve de ejecutividad ya medida directamente por SMS-T18-0199; no hay tres dimensiones adicionales independientes sin paráfrasis o inferencia externa.",
}));
